Repository invoiceninja/ui, pull requests merged in 2023-02, with the labels that each got.

#436 [Bugfix] Reactivity tables
  src/common/atoms/data-table.ts
  src/common/queries/payments.ts
  src/components/DataTable.tsx
  src/pages/credits/common/hooks/useBulkAction.ts
  src/pages/credits/common/hooks/useMarkSent.ts
  src/pages/invoices/edit/hooks/useHandleCancel.ts
  src/pages/invoices/edit/hooks/useMarkPaid.ts
  src/pages/invoices/edit/hooks/useMarkSent.ts
  src/pages/projects/common/hooks/useBulkAction.ts
  src/pages/purchase-orders/common/queries.ts
  src/pages/quotes/common/hooks/useApprove.ts
  src/pages/quotes/common/hooks/useBulkAction.ts
  src/pages/quotes/common/hooks/useMarkSent.ts
  src/pages/recurring-expenses/common/hooks.tsx
  src/pages/recurring-invoices/common/hooks.tsx
  src/pages/tasks/common/hooks/useStart.ts
  src/pages/tasks/common/hooks/useStop.ts
  src/pages/transactions/common/hooks/useBulkAction.tsx
Labels: QA passed

#445 [Feature] Convert To Inovice - Quote Functionality
  src/pages/quotes/common/hooks.tsx
  src/pages/quotes/common/hooks/useBulkAction.ts
  src/pages/settings/company/components/Defaults.tsx
Labels: QA passed

#435 [Feature] Unlock pro button
  src/common/hooks/useUnlockButtonForHosted.ts
  src/common/hooks/useUnlockButtonForSelfHosted.ts
  src/components/layouts/Default.tsx
Labels: QA passed

#428 [Feature] Merge client
  src/components/DataTable.tsx
  src/components/Modal.tsx
  src/components/clients/ClientSelector.tsx
  src/components/dropdown/Dropdown.tsx
  src/pages/clients/common/components/CustomResourcefulActions.tsx
  src/pages/clients/common/components/MergeClientModal.tsx
  src/pages/clients/common/hooks/useActions.tsx
  src/pages/clients/edit/components/Contacts.tsx
  src/pages/clients/index/Clients.tsx
Labels: QA passed

#424 [Cleanup] Quick create popover - Modules | Permissions
  src/common/hooks/entities/useQuickCreateActions.ts
  src/common/hooks/permissions/useHasPermission.ts
  src/components/layouts/Default.tsx
  src/pages/settings/account-management/component/EnabledModules.tsx
  src/pages/transactions/routes.tsx
Labels: QA passed

#362 [Feature] Displaying client gateways
  public/gateway-card-images/american-express.png
  public/gateway-card-images/mastercard.png
  public/gateway-card-images/paypal.png
  public/gateway-card-images/visa.png
  public/gateway-card-images/wepay.svg
  src/common/interfaces/client.ts
  src/pages/clients/show/Client.tsx
  src/pages/clients/show/components/Address.tsx
  src/pages/clients/show/components/Contacts.tsx
  src/pages/clients/show/components/Details.tsx
  src/pages/clients/show/components/GatewayTypeIcon.tsx
  src/pages/clients/show/components/Gateways.tsx
  src/pages/clients/show/components/Standing.tsx
Labels: QA passed

#449 [Cleanup] Client portal - tabs
  src/pages/settings/client-portal/ClientPortal.tsx
Labels: QA passed

#447 [Bugfix] Portrait spelling
  src/pages/settings/invoice-design/components/GeneralSettings.tsx
Labels: QA passed

#446 [Cleanup] Export company - helper text
  src/pages/settings/backup-restore/components/Backup.tsx
Labels: QA passed

#452 [Cleanup] Send time helper text
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed

#451 [Cleanup] Hiding Custom CSS and JS fields
  src/pages/settings/client-portal/components/Customize.tsx
Labels: QA passed

#450 [Cleanup] Currency registration field and fixing bug on registration card
  src/pages/settings/client-portal/components/Registration.tsx
Labels: QA passed

#448 [Cleanup] Invoice design page - tabs
  src/pages/settings/index.ts
  src/pages/settings/invoice-design/InvoiceDesign.tsx
  src/pages/settings/invoice-design/common/hooks.tsx
  src/pages/settings/invoice-design/components/index.ts
  src/pages/settings/invoice-design/index.ts
  src/pages/settings/routes.tsx
Labels: QA passed

#439 [Feature] Emailing Statement
  src/pages/clients/statement/Statement.tsx
Labels: QA passed

#457 [Cleanup] Payment template variables
  src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
  src/pages/settings/templates-and-reminders/common/constants/variables/common-variables.ts
  src/pages/settings/templates-and-reminders/common/constants/variables/payment-variables.ts
Labels: QA passed

#455 [Cleanup] User management - tabs
  src/pages/settings/users/create/Create.tsx
  src/pages/settings/users/edit/Edit.tsx
Labels: QA passed

#462 Fixes for cloning resources
  .env.example
  src/common/helpers.ts
  src/common/queries/products.ts
  src/common/queries/projects.ts
  src/common/queries/tasks.ts
  src/components/clients/ClientSelector.tsx
  src/components/forms/DebouncedCombobox.tsx
  src/pages/credits/common/hooks.tsx
  src/pages/credits/create/Create.tsx
  src/pages/expenses/common/hooks.tsx
  src/pages/expenses/create/Create.tsx
  src/pages/invoices/common/components/ClientSelector.tsx
  src/pages/invoices/common/components/ProductCreate.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/edit/components/Actions.tsx
  src/pages/products/common/components/CreateProduct.tsx
  src/pages/products/common/components/ProductForm.tsx
  src/pages/products/common/hooks.tsx
  src/pages/products/create/Create.tsx
  src/pages/projects/common/hooks.tsx
  src/pages/projects/create/Create.tsx
  src/pages/purchase-orders/common/hooks.tsx
  src/pages/purchase-orders/create/Create.tsx
  src/pages/quotes/common/hooks.tsx
  src/pages/quotes/create/Create.tsx
  src/pages/recurring-expenses/common/hooks.tsx
  src/pages/recurring-expenses/components/Details.tsx
  src/pages/recurring-expenses/create/Create.tsx
  src/pages/recurring-invoices/common/hooks.tsx
  src/pages/recurring-invoices/create/Create.tsx
  src/pages/tasks/common/hooks.tsx
  src/pages/tasks/create/Create.tsx
  src/pages/tasks/edit/components/Actions.tsx
Labels: QA pending

#434 [Feature] Convert currency option - Expense pages
  src/common/interfaces/company.interface.ts
  src/pages/expenses/create/components/AdditionalInfo.tsx
  src/pages/settings/expense-settings/ExpenseSettings.tsx
Labels: QA passed

#472 [Cleanup] Generated numbers - Variables Copy to Clipboard
  src/pages/settings/generated-numbers/clients/Clients.tsx
  src/pages/settings/generated-numbers/credits/Credits.tsx
  src/pages/settings/generated-numbers/expenses/Expenses.tsx
  src/pages/settings/generated-numbers/invoices/Invoices.tsx
  src/pages/settings/generated-numbers/payments/Payments.tsx
  src/pages/settings/generated-numbers/projects/Projects.tsx
  src/pages/settings/generated-numbers/purchase-orders/PurchaseOrders.tsx
  src/pages/settings/generated-numbers/quotes/Quotes.tsx
  src/pages/settings/generated-numbers/recurring-expenses/RecurringExpenses.tsx
  src/pages/settings/generated-numbers/recurring-invoices/RecurringInvoices.tsx
  src/pages/settings/generated-numbers/tasks/Tasks.tsx
  src/pages/settings/generated-numbers/vendors/Vendors.tsx
Labels: QA passed

#471 [Bugfix] Translating custom label keyword
  src/pages/settings/localization/components/CustomLabels.tsx
Labels: QA passed

#469 [Bugfix] Create Bank Account - Permission handling - Invoice Design Optional Chaining
  src/pages/settings/bank-accounts/create/Create.tsx
  src/pages/settings/invoice-design/components/GeneralSettings.tsx
Labels: QA passed

#466 [Cleanup] Expense category - edit action
  src/pages/settings/expense-categories/ExpenseCategories.tsx
Labels: QA passed

#474 [Cleanup] Overdue invoice status badge
  src/pages/invoices/common/components/InvoiceStatus.tsx
  src/pages/invoices/common/hooks/useInvoiceFilters.ts
Labels: QA passed

#480 [Feature] show_email_footer email settings property
  src/common/interfaces/company.interface.ts
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed

#479 [Feature] mark_paid_payment_email company settings property
  src/pages/settings/company/components/Defaults.tsx
Labels: QA passed

#477 [Feature] Auto_bill_standard_invoices implementation
  src/common/interfaces/company.interface.ts
  src/pages/settings/online-payments/OnlinePayments.tsx
Labels: QA passed

#475 [Cleanup] Link To GitHub - Variables
  src/pages/settings/generated-numbers/clients/Clients.tsx
  src/pages/settings/generated-numbers/common/components/LinkToVariables.tsx
  src/pages/settings/generated-numbers/credits/Credits.tsx
  src/pages/settings/generated-numbers/expenses/Expenses.tsx
  src/pages/settings/generated-numbers/invoices/Invoices.tsx
  src/pages/settings/generated-numbers/payments/Payments.tsx
  src/pages/settings/generated-numbers/projects/Projects.tsx
  src/pages/settings/generated-numbers/purchase-orders/PurchaseOrders.tsx
  src/pages/settings/generated-numbers/quotes/Quotes.tsx
  src/pages/settings/generated-numbers/recurring-expenses/RecurringExpenses.tsx
  src/pages/settings/generated-numbers/recurring-invoices/RecurringInvoices.tsx
  src/pages/settings/generated-numbers/tasks/Tasks.tsx
  src/pages/settings/generated-numbers/vendors/Vendors.tsx
Labels: QA passed

#482 [Bugfix] Remaining Cycles - Completed Recurring Expense Status
  src/pages/recurring-expenses/common/components/RecurringExpenseStatus.tsx
  src/pages/recurring-expenses/common/hooks.tsx
Labels: QA passed

#484 [Bugfix] Project query invalidation
  src/pages/projects/Project.tsx
  src/pages/projects/create/Create.tsx
Labels: QA passed

#483 [Cleanup] Project pages 422 errors / Selector components error message
  src/components/clients/ClientSelector.tsx
  src/components/expense-categories/ExpenseCategorySelector.tsx
  src/components/products/ProductSelector.tsx
  src/components/projects/ProjectSelector.tsx
  src/components/users/UserSelector.tsx
  src/components/vendors/VendorSelector.tsx
Labels: more information requested, QA passed

#481 [Feature] Postmark / Mailgun - Email providers
  src/common/interfaces/company.interface.ts
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed, pending revision

#470 [Cleanup] Empty columns - Helper text
  src/pages/settings/invoice-design/components/GeneralSettings.tsx
Labels: more information requested, QA passed, pending revision

#454 [Feature] Bank rules
  src/common/constants/rules.ts
  src/common/interfaces/transaction-rules.ts
  src/common/queries/transaction-rules.ts
  src/pages/settings/bank-accounts/components/transaction-rules/TransactionRules.tsx
  src/pages/settings/bank-accounts/components/transaction-rules/components/RuleModal.tsx
  src/pages/settings/bank-accounts/components/transaction-rules/components/TransactionRuleForm.tsx
  src/pages/settings/bank-accounts/components/transaction-rules/create/Create.tsx
  src/pages/settings/bank-accounts/components/transaction-rules/edit/Edit.tsx
  src/pages/settings/bank-accounts/components/transaction-rules/hooks/useHandleChange.tsx
  src/pages/settings/bank-accounts/components/transaction-rules/hooks/useTransactionRuleColumns.tsx
  src/pages/settings/bank-accounts/index.ts
  src/pages/settings/bank-accounts/index/BankAccounts.tsx
  src/pages/settings/routes.tsx
Labels: more information requested, QA passed

#460 [Cleanup] Update all records - Invoice design
  src/pages/settings/common/hooks/useHandleCompanySave.tsx
  src/pages/settings/invoice-design/common/atoms.ts
  src/pages/settings/invoice-design/components/GeneralSettings.tsx
Labels: QA passed, pending revision

#488 [Cleanup] UI After Restored Company
  src/components/import/UploadImport.tsx
  src/pages/settings/backup-restore/components/Restore.tsx
Labels: QA passed

#489 [Bugfix] Microsoft button centering
  src/pages/authentication/components/SignInProviders.tsx
Labels: QA passed

#473 [Feature] React settings - Show pdf functionality
  src/common/hooks/useReactSettings.ts
  src/common/interfaces/company-user.ts
  src/pages/credits/create/Create.tsx
  src/pages/credits/edit/Edit.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/purchase-orders/create/Create.tsx
  src/pages/purchase-orders/edit/Edit.tsx
  src/pages/quotes/create/Create.tsx
  src/pages/quotes/edit/Edit.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
  src/pages/settings/routes.tsx
  src/pages/settings/user/common/hooks/useUserDetailsTabs.tsx
  src/pages/settings/user/components/Preferences.tsx
  src/pages/settings/user/components/index.ts
  src/pages/settings/user/index.ts
Labels: more information requested, QA passed

#498 [BugFix] PDF Preview - Credits, Invoices, Quotes and PurchaseOrders
  src/pages/credits/edit/Edit.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/quotes/edit/Edit.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
Labels: QA passed
