Repository invoiceninja/ui, pull requests merged in 2023-06, with the labels that each got.

#701 Improve combobox accessibility
  src/components/forms/Combobox.tsx
  src/pages/invoices/common/components/ProductCreate.tsx
Labels: QA pending

#703 Add default headers
  src/common/queries/common/headers.ts
  src/pages/settings/user/components/Connect.tsx
Labels: QA passed

#704 Fixes for query invalidation
  src/components/forms/Combobox.tsx
  src/pages/products/common/hooks.tsx
Labels: QA passed

#711 Add toggle for notification link preference
  src/common/hooks/useReactSettings.ts
  src/common/interfaces/company-user.ts
  src/pages/settings/user/components/Preferences.tsx
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/lt/lt.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nb_NO/nb_NO.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/ru_RU/ru_RU.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sq/sq.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/th/th.json
  src/resources/lang/tr_TR/tr_TR.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#706 [Bugfix] Password change
  src/pages/settings/user/UserDetails.tsx
  src/pages/settings/user/components/Password.tsx
Labels: QA passed

#674 [Feature] Gatway Pages Refactoring
  public/gateway-card-images/authorize-net.png
  public/gateway-card-images/braintree.svg.png
  public/gateway-card-images/checkout.jpg
  public/gateway-card-images/eway.png
  public/gateway-card-images/forte.png
  public/gateway-card-images/gocardless.png
  public/gateway-card-images/mollie.png
  public/gateway-card-images/payfast.png
  public/gateway-card-images/paytrace.svg
  public/gateway-card-images/razorpay.png
  public/gateway-card-images/square.svg.png
  public/gateway-card-images/stripe.svg
  src/common/queries/company-gateways.ts
  src/components/TabGroup.tsx
  src/pages/clients/show/components/GatewayTypeIcon.tsx
  src/pages/settings/gateways/create/Create.tsx
  src/pages/settings/gateways/create/hooks/useHandleCreate.ts
  src/pages/settings/gateways/index/Gateways.tsx
Labels: QA passed

#716 Hosted client portal domain
  src/common/interfaces/company.interface.ts
  src/components/HelpSidebarIcons.tsx
  src/pages/settings/client-portal/components/Settings.tsx
  src/pages/settings/generated-numbers/clients/Clients.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Settings.tsx
Labels: QA passed

#718 White label link
  src/components/layouts/Default.tsx
  src/env.d.ts
Labels: QA passed

#726 Fixes for redundant queries
  src/pages/settings/common/hooks/useHandleCompanySave.tsx
  src/pages/settings/localization/common/atoms.ts
  src/pages/settings/localization/components/Settings.tsx
Labels: QA passed

#724 Add credit balance to client overview
  src/common/interfaces/client.ts
  src/pages/clients/show/components/Standing.tsx
Labels: QA passed

#722 Fixes for quote status
  src/pages/quotes/common/components/QuoteStatus.tsx
Labels: QA passed

#646 [Cleanup] Date | Time Formatting
  package-lock.json
  package.json
  src/App.tsx
  src/common/hooks/useCompanyTimeFormat.ts
  src/common/hooks/useResolveDayJSLocale.ts
  src/components/DropdownDateRangePicker.tsx
  src/components/forms/Datepicker.tsx
  src/components/forms/InputField.tsx
  src/components/forms/TimePicker.tsx
  src/components/forms/TimePickerPopperSection.tsx
  src/pages/payments/refund/Refund.tsx
  src/pages/projects/common/hooks/useInvoiceProject.tsx
  src/pages/settings/generated-numbers/components/Settings.tsx
  src/pages/tasks/common/components/TaskTable.tsx
  src/pages/tasks/common/hooks/useInvoiceTask.ts
  src/pages/tasks/kanban/components/EditSlider.tsx
  src/pages/tasks/kanban/components/ViewSlider.tsx
  src/pages/transactions/components/Details.tsx
  src/pages/transactions/components/ListBoxItem.tsx
  src/pages/transactions/index/Transactions.tsx
  tailwind.config.js
Labels: QA passed

#721 Fixes for partially stale combobox cache
  src/components/clients/ClientSelector.tsx
  src/components/forms/Combobox.tsx
  src/components/products/ProductSelector.tsx
Labels: QA passed

#720 Fixes for incorrect casting
  src/common/interfaces/company.interface.ts
  src/pages/settings/generated-numbers/components/Settings.tsx
Labels: QA passed

#715 [Feature] Default Password Timeout | Password Confirmation Modal
  src/common/atoms/password-confirmation.ts
  src/common/interfaces/company.interface.ts
  src/components/DocumentsTable.tsx
  src/components/PasswordConfirmation.tsx
  src/pages/clients/common/components/MergeClientModal.tsx
  src/pages/clients/common/hooks/usePurgeClient.ts
  src/pages/settings/account-management/component/DangerZone.tsx
  src/pages/settings/account-management/component/SecuritySettings.tsx
  src/pages/settings/company/documents/components/Table.tsx
  src/pages/settings/integrations/api-tokens/Create.tsx
  src/pages/settings/integrations/api-tokens/Edit.tsx
  src/pages/settings/user/UserDetails.tsx
  src/pages/settings/users/create/Create.tsx
  src/pages/settings/users/edit/Edit.tsx
Labels: QA passed

#719 [Cleanup] Notifications | User Details
  src/pages/settings/user/common/hooks/useNotificationOptions.ts
  src/pages/settings/user/components/Notifications.tsx
Labels: QA passed

#729 [Cleanup] Email Confirmation Banner | Implementation
  src/App.tsx
  src/components/Banner.tsx
  src/components/EmailConfirmationBanner.tsx
  src/components/layouts/Default.tsx
  src/components/layouts/components/DesktopSidebar.tsx
Labels: QA passed

#734 Verification banners
  package-lock.json
  package.json
  src/App.tsx
  src/components/VerifyModal.tsx
  src/components/banners/ActivateCompany.tsx
  src/components/banners/VerifyEmail.tsx
  src/components/banners/VerifyPhone.tsx
  src/components/layouts/Default.tsx
Labels: QA passed

#737 Updated translations
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/lt/lt.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nb_NO/nb_NO.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/ru_RU/ru_RU.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sq/sq.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/th/th.json
  src/resources/lang/tr_TR/tr_TR.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#742 Add blank option for subscriptions frequency
  src/components/layouts/common/hooks.ts
  src/pages/settings/subscriptions/common/components/Settings.tsx
  src/pages/settings/subscriptions/create/Create.tsx
  src/pages/settings/subscriptions/edit/Edit.tsx
  src/pages/settings/subscriptions/index/Subscriptions.tsx
Labels: QA passed

#747 fixes for charts
  src/pages/dashboard/components/Totals.tsx
Labels: QA passed

#744 Hungarian + Khmer translations
  src/resources/lang/de/de.json
  src/resources/lang/en/en.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/hu/hu.json
  src/resources/lang/km_KH/km_KH.json
Labels: QA passed

#753 Filter for showing password modal
  src/components/PasswordConfirmation.tsx
Labels: QA passed

#756 Fixes for date selectors
  package-lock.json
  package.json
  src/components/DropdownDateRangePicker.tsx
  src/pages/dashboard/components/Totals.tsx
Labels: QA passed

#757 Fixes for footers that are missing props
  src/pages/credits/common/components/CreditFooter.tsx
  src/pages/quotes/common/components/QuoteFooter.tsx
  src/pages/recurring-invoices/common/components/InvoiceFooter.tsx
Labels: QA passed

#758 Do not show pdf previews if disabled
  src/pages/invoices/email/components/Mailer.tsx
Labels: QA passed

#759 Fixes for mail content when it extends
  src/pages/invoices/email/components/Mailer.tsx
  src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
Labels: QA passed

#765 Rework logic for password confirmation dialogue for oauth
  src/common/interfaces/company.interface.ts
  src/components/PasswordConfirmation.tsx
  src/pages/settings/user/UserDetails.tsx
Labels: QA passed

#764 Product descriptions in selector
  src/components/forms/Combobox.tsx
  src/components/products/ProductSelector.tsx
Labels: QA passed

#773 Add silencer to view portal links
  src/pages/invoices/common/components/ClientSelector.tsx
  src/pages/invoices/common/helpers/open-client-portal.ts
Labels: QA passed

#772 Set todays date when cloning
  src/pages/credits/common/hooks.tsx
  src/pages/invoices/edit/components/Actions.tsx
  src/pages/purchase-orders/common/hooks.tsx
  src/pages/quotes/common/hooks.tsx
  src/pages/recurring-invoices/common/components/InvoiceDetails.tsx
  src/pages/recurring-invoices/common/hooks.tsx
Labels: QA passed

#770 Refactor updating all resources (invoice design)
  src/pages/settings/common/hooks/useHandleCompanySave.tsx
  src/pages/settings/invoice-design/common/atoms.ts
  src/pages/settings/invoice-design/pages/general-settings/GeneralSettings.tsx
  src/pages/settings/invoice-design/pages/general-settings/components/GeneralSettings.tsx
Labels: QA passed

#763 Replace time picker with native elements
  src/components/forms/TimePicker.tsx
  src/components/forms/TimePickerPopperSection.tsx
  src/pages/tasks/common/components/TaskTable.tsx
  src/pages/tasks/kanban/components/EditSlider.tsx
Labels: QA passed

#751 Implement Inclusive tax calculations
  src/common/helpers/invoices/invoice-item-sum-inclusive.ts
  src/common/helpers/invoices/invoice-sum-inclusive.ts
  src/common/helpers/invoices/invoice-sum.ts
  src/pages/credits/common/atoms.ts
  src/pages/credits/common/hooks.tsx
  src/pages/credits/create/Create.tsx
  src/pages/invoices/common/atoms.ts
  src/pages/invoices/common/components/InvoiceTotals.tsx
  src/pages/invoices/common/hooks/useResolveTotalVariable.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/create/hooks/useInvoiceUtilities.ts
  src/pages/purchase-orders/create/Create.tsx
  src/pages/purchase-orders/edit/Edit.tsx
  src/pages/purchase-orders/edit/hooks/useCalculateInvoiceSum.ts
  src/pages/purchase-orders/edit/hooks/useHandleLineItemPropertyChange.ts
  src/pages/purchase-orders/edit/hooks/useHandleProductChange.ts
  src/pages/quotes/common/atoms.ts
  src/pages/quotes/common/hooks.tsx
  src/pages/quotes/create/Create.tsx
  src/pages/recurring-invoices/common/atoms.ts
  src/pages/recurring-invoices/common/hooks.tsx
  src/pages/recurring-invoices/create/Create.tsx
  tests/unit/helpers/invoice-sum-inclusive.test.ts
Labels: QA passed, pending merge

#754 Task invoice description filter
  src/common/interfaces/company.interface.ts
  src/components/DropdownDateRangePicker.tsx
  src/components/PasswordConfirmation.tsx
  src/components/forms/Combobox.tsx
  src/pages/clients/edit/components/Details.tsx
  src/pages/clients/show/components/Standing.tsx
  src/pages/credits/common/components/CreditFooter.tsx
  src/pages/payments/common/hooks/usePaymentFilters.tsx
  src/pages/quotes/common/components/QuoteFooter.tsx
  src/pages/quotes/common/components/QuoteStatus.tsx
  src/pages/recurring-invoices/common/components/InvoiceFooter.tsx
  src/pages/settings/account-management/component/EnabledModules.tsx
  src/pages/settings/client-portal/components/Registration.tsx
  src/pages/settings/client-portal/components/Settings.tsx
  src/pages/settings/localization/components/Settings.tsx
  src/pages/settings/task-settings/TaskSettings.tsx
  src/pages/settings/user/components/Preferences.tsx
  src/pages/tasks/common/hooks.tsx
  src/pages/tasks/common/hooks/useInvoiceTask.ts
  src/pages/transactions/routes.tsx
  tests/unit/helpers/users/user.test.ts
Labels: QA passed, pending merge

#768 Improve client selector UX
  src/pages/credits/edit/Edit.tsx
  src/pages/invoices/common/components/ClientSelector.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/quotes/edit/Edit.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
Labels: QA passed

#778 Fixes for combobox showing nothing on empty value
  src/components/forms/Combobox.tsx
Labels: QA passed

#781 Hide licence management for demo
  src/pages/settings/account-management/component/Plan.tsx
Labels: QA passed

#777 Improved logic for formatting combox labels
  src/components/forms/Combobox.tsx
  src/components/products/ProductSelector.tsx
  src/pages/credits/common/components/CreditFooter.tsx
Labels: QA passed

#783 Fixes for padding
  src/pages/settings/generated-numbers/components/Settings.tsx
Labels: QA passed

#787 Fixes for cloning - unset props on clone.
  src/pages/credits/common/hooks.tsx
  src/pages/invoices/edit/components/Actions.tsx
  src/pages/purchase-orders/common/hooks.tsx
  src/pages/quotes/common/hooks.tsx
  src/pages/recurring-invoices/common/hooks.tsx
Labels: QA passed

#788 Fixes for signup crash
  src/components/banners/VerifyPhone.tsx
Labels: QA passed

#790 Fixes for missing header
  src/common/queries/common/headers.ts
Labels: QA passed

#789 Fixes for filtering line items
  src/common/interfaces/invoice-item.ts
  src/pages/credits/create/Create.tsx
  src/pages/credits/edit/Edit.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/quotes/edit/Edit.tsx
  src/pages/recurring-invoices/create/Create.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
Labels: QA passed

#746 Protect document downloads with auth
  src/components/DocumentsTable.tsx
Labels: QA passed

#794 Fixes for payment types
  src/common/constants/payment-type.ts
  src/common/enums/payment-type.ts
Labels: QA passed

#767 Projects overview page
  src/common/interfaces/project.ts
  src/common/queries/invoices.ts
  src/pages/projects/common/hooks.tsx
  src/pages/projects/common/hooks/useBulkAction.ts
  src/pages/projects/routes.tsx
  src/pages/projects/show/Show.tsx
  src/pages/tasks/create/Create.tsx
Labels: QA passed

#752 Add "All Time" to scheduled statements date range; allow excluding clients with no matching statements
  src/common/interfaces/schedule.ts
  src/pages/clients/common/hooks/useScheduleStatement.tsx
  src/pages/clients/statement/Statement.tsx
  src/pages/invoices/common/hooks/useScheduleEmailRecord.tsx
  src/pages/settings/schedules/common/components/EmailStatement.tsx
  src/pages/settings/schedules/common/hooks/useFormatSchedulePayload.tsx
  src/pages/settings/schedules/common/hooks/useHandleChange.tsx
  src/pages/settings/schedules/create/Create.tsx
  src/resources/lang/en/en.json
Labels: QA passed

#797 Fallback for PDF previews on Android
  src/pages/invoices/common/components/InvoiceViewer.tsx
  src/pages/invoices/email/components/Mailer.tsx
Labels: QA passed

#799 [Bugfix] Client Create Modal | Client Combobox
  src/components/clients/ClientSelector.tsx
  src/pages/clients/edit/components/AdditionalInfo.tsx
  src/pages/clients/edit/components/Contacts.tsx
  src/pages/clients/edit/components/Details.tsx
  src/pages/invoices/common/components/ClientCreate.tsx
Labels: QA passed

#800 Add payment type cash
  src/common/constants/payment-type.ts
  src/common/enums/payment-type.ts
Labels: QA passed

#802 Fixes for tax ids
  src/common/constants/blank-line-item.ts
  src/common/interfaces/invoice-item.ts
  src/pages/invoices/common/hooks/useHandleProductChange.ts
  tests/helpers/data/invoice.ts
  tests/helpers/data/invoice_item.ts
  tests/unit/helpers/invoice-sum-inclusive.test.ts
Labels: QA passed

#803 Contacts password feature
  src/common/queries/clients.ts
  src/common/queries/invoices.ts
  src/pages/clients/create/Create.tsx
  src/pages/clients/edit/Edit.tsx
  src/pages/clients/edit/components/Contacts.tsx
  src/pages/clients/show/Client.tsx
  src/pages/clients/statement/Statement.tsx
Labels: QA passed

#805 [Bugfix] Adding Validation | Emailing Pages
  src/common/hooks/emails/useHandleSend.ts
  src/pages/invoices/email/components/Mailer.tsx
Labels: QA passed

#810 [Bugfix] Query Invalidation Across the App
  src/common/queries/clients.ts
  src/common/queries/company-gateways.ts
  src/components/DataTable.tsx
  src/pages/settings/system-logs/SystemLog.tsx
  src/pages/tasks/common/components/CreateTaskModal.tsx
  src/pages/transactions/components/TransactionMatchDetails.tsx
Labels: QA passed

#792 Conditionally mutating company
  src/common/hooks/useCurrentCompany.ts
  src/pages/clients/edit/Edit.tsx
  src/pages/credits/common/hooks.tsx
  src/pages/invoices/edit/hooks/useInvoiceSave.ts
  src/pages/quotes/common/hooks.tsx
  src/pages/settings/common/hooks/useHandleCompanySave.tsx
  src/pages/tasks/edit/Edit.tsx
  src/pages/vendors/components/CreateVendorForm.tsx
  src/pages/vendors/edit/Edit.tsx
Labels: QA passed

#813 Fixes for payment notification presets
  src/common/constants/payment-type.ts
  src/common/enums/payment-type.ts
  src/pages/payments/create/Create.tsx
  src/pages/tasks/common/components/TaskDetails.tsx
  src/pages/tasks/create/Create.tsx
Labels: QA passed

#817 Fixes for template previews
  src/pages/clients/show/components/Address.tsx
  src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
Labels: QA passed

#824 Updated translations
  src/resources/lang/en/en.json
Labels: QA passed

#822 Fixes for previews
  src/pages/invoices/common/components/InvoicePreview.tsx
Labels: QA passed

#823 Fixes for shipping address
  src/pages/clients/edit/components/address/ShippingAddress.tsx
Labels: QA passed

#821 Fixes for invoice invalidation after payment applied
  src/pages/payments/create/hooks/useSave.ts
Labels: QA passed

#819 Improve contact editing
  src/components/CopyToClipBoardIconOnly.tsx
  src/components/emails/Contact.tsx
  src/pages/clients/edit/components/Contacts.tsx
  src/pages/invoices/common/components/ClientSelector.tsx
Labels: QA passed

#811 [Bugfix] Project Dropdown | Project Client
  src/pages/projects/common/hooks.tsx
  src/pages/projects/common/hooks/useInvoiceProject.tsx
  src/pages/projects/show/Show.tsx
Labels: QA passed

#812 [Bugfix] Stripe Displaying | Hosted Platform
  src/components/TabGroup.tsx
  src/pages/settings/gateways/create/Create.tsx
  src/pages/settings/gateways/create/hooks/useHandleCreate.ts
  src/pages/settings/gateways/edit/Edit.tsx
Labels: QA passed

#826 [Bugfix] Payment Page | Displaying Invoices & Credits
  src/pages/payments/Payment.tsx
  src/pages/payments/edit/hooks/useSave.ts
Labels: QA passed

#831 [Bugfix] Gateways Production Query Invalidation Fixes
  src/common/queries/company-gateways.ts
  src/pages/settings/gateways/create/hooks/useHandleCreate.ts
  src/pages/settings/gateways/edit/hooks/useHandleUpdate.ts
Labels: QA passed

#832 Refactor for activities
  src/common/interfaces/activity-record.ts
  src/pages/dashboard/components/Activity.tsx
  src/pages/dashboard/hooks/useGenerateActivityElement.tsx
Labels: QA passed

#838 Fixes for duration and passing rates into tasks
  src/common/interfaces/project.ts
  src/pages/projects/common/hooks.tsx
  src/pages/projects/show/Show.tsx
  src/pages/tasks/common/helpers/calculate-time.ts
  src/pages/tasks/create/Create.tsx
Labels: QA passed

#837 Updates for queries when in client overview
  src/pages/clients/show/pages/Payments.tsx
Labels: QA passed

#836 Fixes for bulk actions in users table
  src/pages/settings/users/index/Users.tsx
Labels: QA passed

#835 Fixes for applying payments button
  src/pages/payments/apply/Apply.tsx
Labels: QA passed

#834 Update app metadata
  public/logo180.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: QA passed

#830 [Bugfix] Displaying 422 On Some Pages
  src/pages/clients/create/Create.tsx
  src/pages/clients/edit/Edit.tsx
  src/pages/clients/edit/components/AdditionalInfo.tsx
  src/pages/clients/edit/components/Address.tsx
  src/pages/clients/edit/components/Contacts.tsx
  src/pages/clients/edit/components/Details.tsx
  src/pages/clients/edit/components/address/BillingAddress.tsx
  src/pages/clients/edit/components/address/ShippingAddress.tsx
  src/pages/credits/common/components/CreditFooter.tsx
  src/pages/credits/create/Create.tsx
  src/pages/credits/edit/Edit.tsx
  src/pages/invoices/common/components/ClientCreate.tsx
  src/pages/invoices/common/components/InvoiceFooter.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/purchase-orders/edit/components/Footer.tsx
  src/pages/quotes/common/components/QuoteFooter.tsx
  src/pages/quotes/create/Create.tsx
  src/pages/quotes/edit/Edit.tsx
  src/pages/recurring-invoices/common/components/InvoiceFooter.tsx
  src/pages/recurring-invoices/create/Create.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
Labels: QA passed

#815 [Bugfix] Activate Company Banner & Settings Break App On New Sign Up
  src/components/banners/ActivateCompany.tsx
  src/components/banners/VerifyPhone.tsx
  src/components/layouts/Default.tsx
Labels: QA passed

#843 Improve payment overview
  src/common/interfaces/payment.ts
  src/pages/payments/create/Create.tsx
  src/pages/payments/edit/PaymentOverviewInvoice.tsx
Labels: QA passed

#840 Change chart queries date strings
  src/components/DropdownDateRangePicker.tsx
  src/pages/dashboard/components/Activity.tsx
  src/pages/dashboard/components/ExpiredQuotes.tsx
  src/pages/dashboard/components/PastDueInvoices.tsx
  src/pages/dashboard/components/RecentPayments.tsx
  src/pages/dashboard/components/Totals.tsx
  src/pages/dashboard/components/UpcomingInvoices.tsx
  src/pages/dashboard/components/UpcomingQuotes.tsx
Labels: QA passed

#839 Fixes for showing active tax rates only.
  src/pages/invoices/common/components/InvoiceTotals.tsx
  src/pages/settings/tax-settings/components/Selector.tsx
Labels: QA passed

#833 Fixes for queries
  src/common/helpers/invoices/invoice-sum-inclusive.ts
  src/common/helpers/invoices/invoice-sum.ts
  src/pages/invoices/common/hooks/useResolveTotalVariable.tsx
  src/pages/payments/apply/Apply.tsx
  src/pages/payments/edit/PaymentOverviewInvoice.tsx
Labels: QA passed

#856 Fixes for nullables
  src/components/forms/Combobox.tsx
Labels: QA passed

#855 Ensure default taxes are set on entities on create
  src/pages/credits/create/Create.tsx
  src/pages/quotes/create/Create.tsx
Labels: QA passed

#852 Improve & migrate selectors
  src/components/forms/Combobox.tsx
  src/components/projects/ProjectSelector.tsx
  src/components/users/UserSelector.tsx
  src/pages/invoices/common/components/InvoiceFooter.tsx
Labels: QA passed

#848 Invoice Expenses
  src/common/interfaces/expense.ts
  src/common/interfaces/invoice-item.ts
  src/common/queries/expenses.ts
  src/components/expense-categories/ExpenseCategorySelector.tsx
  src/components/projects/ProjectSelector.tsx
  src/components/tax-rates/TaxRateSelector.tsx
  src/components/users/UserSelector.tsx
  src/components/vendors/VendorSelector.tsx
  src/pages/expenses/common/hooks.tsx
  src/pages/expenses/common/useInvoiceExpense.ts
  src/pages/expenses/create/components/Details.tsx
  src/pages/expenses/create/components/Taxes.tsx
  src/pages/expenses/edit/Edit.tsx
  src/pages/expenses/edit/hooks/useSave.ts
  src/pages/expenses/index/Expenses.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/projects/index/Projects.tsx
  src/pages/tasks/common/hooks/useInvoiceTask.ts
Labels: QA passed

#864 Fixes for isNan
  src/pages/payments/create/Create.tsx
Labels: QA passed

#863 Fixes for charts
  src/components/DropdownDateRangePicker.tsx
  src/pages/dashboard/components/Totals.tsx
Labels: QA passed

#862 Fixes for queries for adding expense to invoice
  src/pages/expenses/common/hooks.tsx
Labels: QA passed

#857 Refactor send reminders toggle
  src/pages/clients/edit/components/AdditionalInfo.tsx
Labels: pending revision

#859 [Bugfix] Payment Creation 422 For Invoices And Credits
  src/pages/payments/create/Create.tsx
Labels: QA passed

#853 [Feature] Bulk Invoice Project
  src/components/DataTable.tsx
  src/pages/credits/index/Credits.tsx
  src/pages/invoices/create/hooks/useHandleCreate.ts
  src/pages/invoices/index/Invoices.tsx
  src/pages/projects/common/hooks.tsx
  src/pages/projects/common/hooks/useCombineProjectsTasks.ts
  src/pages/projects/index/Projects.tsx
  src/pages/purchase-orders/index/PurchaseOrders.tsx
  src/pages/quotes/index/Quotes.tsx
Labels: QA passed, waiting for @beganovich

#869 Add missing selector for gmail users
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed

#868 Fixes for debounce + nan
  src/components/forms/DecimalNumberInput.tsx
  src/pages/invoices/common/hooks/useResolveInputField.tsx
Labels: QA passed

#867 Fixes for mailer naming
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed

#866 [Cleanup] Payment Settings Replacement
  src/common/interfaces/company.interface.ts
  src/pages/settings/company/components/Defaults.tsx
  src/pages/settings/online-payments/OnlinePayments.tsx
Labels: QA passed

#877 Remove tinymce context menu
  src/components/forms/MarkdownEditor.tsx
Labels: QA passed

#876 temporary disablement of send reminders config
  src/pages/clients/edit/components/AdditionalInfo.tsx
Labels: QA passed
