Repository invoiceninja/ui, pull requests merged in 2023-10, with the labels that each got.

#1155 Allow UI to show calc tax option for all of EU
  src/common/hooks/useCalculateTaxesRegion.ts
Labels: QA passed

#1157 [Bugfix] Edit Api Tokens
  src/common/queries/api-tokens.ts
Labels: QA passed

#1152 Scope pasting data images
  src/components/forms/MarkdownEditor.tsx
Labels: QA passed

#1162 [Bugfix] Add To Invoice Expense Action & Little Logic Refactoring For Action
  src/pages/expenses/common/components/AddToInvoiceAction.tsx
  src/pages/expenses/common/hooks.tsx
Labels: QA passed

#1161 Fixes for payment currency
  src/components/ConvertCurrency.tsx
  src/pages/payments/create/Create.tsx
  src/pages/payments/edit/Edit.tsx
Labels: QA passed

#1160 [Cleanup] Correcting Route For Downloading Invoice Documents
  src/pages/invoices/common/hooks/useCustomBulkActions.tsx
Labels: QA passed

#1159 [Cleanup] Task Statuses Dropdown | Task Tables
  src/components/StatusBadge.tsx
  src/pages/tasks/common/components/TaskStatus.tsx
  src/pages/tasks/common/components/TaskStatusesDropdown.tsx
  src/pages/tasks/common/hooks/useUpdateTask.ts
  src/pages/tasks/edit/Edit.tsx
Labels: QA passed

#1167 Fixes for formatting when invoicing a project
  src/pages/projects/common/hooks/useInvoiceProject.tsx
  src/pages/tasks/common/hooks/useAddTasksOnInvoice.ts
  src/pages/tasks/common/hooks/useInvoiceTask.ts
Labels: QA passed

#1172 Updated translations
  src/resources/lang/en/en.json
Labels: QA passed

#1168 [Feature] Additional Custom Filters | Upcoming & Converted | Quotes
  src/pages/quotes/common/hooks.tsx
Labels: QA passed

#1164 [Cleanup] Invoice Edit Page CTAs
  src/components/ResourceActions.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/invoices/edit/components/Actions.tsx
  src/pages/invoices/edit/components/CommonActions.tsx
Labels: QA passed

#1178 20231010 resolve contact in activity
  src/common/interfaces/invoice-activity.ts
  src/pages/invoices/common/components/InvoiceSlider.tsx
Labels: QA passed

#1166 [Cleanup] 2FA Workflow When a User Changes Their Phone Number and Saves It
  .env.example
  src/pages/settings/user/UserDetails.tsx
  src/pages/settings/user/common/components/TwoFactorAuthenticationModals.tsx
  src/pages/settings/user/components/TwoFactorAuthentication.tsx
Labels: QA passed

#1179 Ensure type id is set on payment on creation
  src/pages/payments/create/Create.tsx
Labels: QA passed

#1109 Centralised place for user preferences
  .eslintrc.json
  src/common/hooks/useReactSettings.ts
  src/pages/settings/user/UserDetails.tsx
  src/pages/settings/user/components/Preferences.tsx
Labels: QA passed

#1171 [Cleanup] Adding Refund && Apply Tabs On Payment Edit Page && Adjustment For Label On Invoices Dropdown For Refund Page
  src/pages/payments/Payment.tsx
  src/pages/payments/apply/Apply.tsx
  src/pages/payments/edit/hooks/useTabs.ts
  src/pages/payments/refund/Refund.tsx
Labels: QA passed

#1132 [Cleanup] Settings Pages Checkbox Implementation For Client/Group Settings && Changing Few Fields Type To Number
  src/common/constants/blank-company-settings.ts
  src/common/constants/group-settings.ts
  src/common/hooks/useDisableSettingsField.ts
  src/common/hooks/useResolveDateFormat.ts
  src/common/hooks/useResolveDesign.ts
  src/common/hooks/useResolveGateway.ts
  src/common/hooks/useResolvePaymentTerm.ts
  src/common/hooks/useResolvePaymentType.ts
  src/common/hooks/useResolveTimeZone.ts
  src/common/interfaces/company.interface.ts
  src/components/PropertyCheckbox.tsx
  src/components/SettingsLabel.tsx
  src/components/cards/Element.tsx
  src/components/forms/ColorPicker.tsx
  src/components/forms/InputField.tsx
  src/components/forms/MarkdownEditor.tsx
  src/components/forms/Radio.tsx
  src/components/forms/SelectField.tsx
  src/components/forms/Toggle.tsx
  src/pages/clients/common/hooks/useUpdateClientSettings.ts
  src/pages/settings/client-portal/components/Authorization.tsx
  src/pages/settings/client-portal/components/Customize.tsx
  src/pages/settings/client-portal/components/Messages.tsx
  src/pages/settings/client-portal/components/Settings.tsx
  src/pages/settings/company/components/Address.tsx
  src/pages/settings/company/components/Defaults.tsx
  src/pages/settings/company/components/Details.tsx
  src/pages/settings/email-settings/EmailSettings.tsx
  src/pages/settings/generated-numbers/GeneratedNumbers.tsx
  src/pages/settings/generated-numbers/clients/Clients.tsx
  src/pages/settings/generated-numbers/components/Settings.tsx
  src/pages/settings/generated-numbers/credits/Credits.tsx
  src/pages/settings/generated-numbers/expenses/Expenses.tsx
  src/pages/settings/generated-numbers/invoices/Invoices.tsx
  src/pages/settings/generated-numbers/payments/Payments.tsx
  src/pages/settings/generated-numbers/projects/Projects.tsx
  src/pages/settings/generated-numbers/purchase-orders/PurchaseOrders.tsx
  src/pages/settings/generated-numbers/quotes/Quotes.tsx
  src/pages/settings/generated-numbers/recurring-expenses/RecurringExpenses.tsx
  src/pages/settings/generated-numbers/recurring-invoices/RecurringInvoices.tsx
  src/pages/settings/generated-numbers/tasks/Tasks.tsx
  src/pages/settings/generated-numbers/vendors/Vendors.tsx
  src/pages/settings/group-settings/common/components/GroupSettingsProperties.tsx
  src/pages/settings/group-settings/common/hooks/useHandleUpdate.ts
  src/pages/settings/group-settings/common/hooks/useResolvePropertyLabel.ts
  src/pages/settings/group-settings/common/hooks/useResolvePropertyValue.ts
  src/pages/settings/group-settings/edit/Edit.tsx
  src/pages/settings/invoice-design/pages/general-settings/components/GeneralSettings.tsx
  src/pages/settings/localization/components/Settings.tsx
  src/pages/settings/online-payments/OnlinePayments.tsx
  src/pages/settings/products/ProductSettings.tsx
  src/pages/settings/subscriptions/common/components/Settings.tsx
  src/pages/settings/task-settings/TaskSettings.tsx
  src/pages/settings/tax-settings/components/Selector.tsx
  src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
  src/pages/settings/workflow-settings/components/Invoices.tsx
  src/pages/settings/workflow-settings/components/Quotes.tsx
Labels: QA passed, pending revision

#1181 Playwright gh actions
  .github/workflows/playwright.yml
  playwright.config.ts
Labels: QA passed

#1193 Add user custom fields
  src/pages/settings/users/edit/components/Details.tsx
Labels: QA passed

#1192 Updated translations
  src/pages/settings/online-payments/OnlinePayments.tsx
  src/pages/settings/tax-settings/TaxSettings.tsx
  src/resources/lang/en/en.json
Labels: QA passed

#1191 Add new expense setting prop
  src/pages/settings/expense-settings/ExpenseSettings.tsx
Labels: QA passed

#1190 Add Embed documents option back to company settings
  src/pages/settings/invoice-design/pages/general-settings/components/GeneralSettings.tsx
Labels: QA passed

#1189 [Cleanup] Clickability On Rows | Improvement
  src/components/DataTable.tsx
  src/components/tables/Td.tsx
Labels: QA passed

#1187 [Feature] Expense Category Dropdown | Expenses Tables
  src/common/queries/expense-categories.ts
  src/pages/clients/show/pages/Expenses.tsx
  src/pages/expenses/common/components/ExpenseCategory.tsx
  src/pages/expenses/common/hooks.tsx
  src/pages/expenses/edit/hooks/useSave.ts
  src/pages/settings/expense-categories/components/CreateExpenseCategoryModal.tsx
  src/pages/vendors/show/pages/Expenses.tsx
Labels: QA passed

#1197 Fixes for base path of kanban queries
  src/pages/tasks/common/components/CreateTaskModal.tsx
  src/pages/tasks/kanban/Kanban.tsx
Labels: QA passed

#1196 Add language id to user model
  src/App.tsx
  src/common/interfaces/user.ts
  src/pages/settings/user/components/Details.tsx
  tests/unit/helpers/users/user.test.ts
Labels: QA passed

#1206 Add fields for export maps
  src/common/constants/exports/invoice-map.ts
Labels: QA passed

#1211 Fixes for auto bill recurring
  src/pages/recurring-invoices/create/Create.tsx
Labels: QA passed

#1210 [Cleanup] Sms Verification Modal Improvement | Debounce etc. && Resolving Bug With VITE_FEATURE_2FA Env Variable
  .env.example
  src/pages/settings/user/common/components/TwoFactorAuthenticationModals.tsx
  src/pages/settings/user/components/SmsVerificationModal.tsx
Labels: QA passed

#1207 Combobox improvements
  src/common/generic/DesignSelector.tsx
  src/components/TestingPage.tsx
  src/components/clients/ClientSelector.tsx
  src/components/expense-categories/ExpenseCategorySelector.tsx
  src/components/forms/Combobox.tsx
  src/components/products/ProductSelector.tsx
  src/components/projects/ProjectSelector.tsx
  src/components/task-statuses/TaskStatusSelector.tsx
  src/components/tax-rates/TaxRateSelector.tsx
  src/components/users/UserSelector.tsx
  src/components/vendors/VendorSelector.tsx
  src/pages/payments/apply/Apply.tsx
  src/pages/payments/create/Create.tsx
  src/pages/settings/schedules/common/components/EmailRecord.tsx
  src/pages/settings/subscriptions/common/components/Overview.tsx
  src/pages/transactions/components/BankAccountSelector.tsx
Labels: QA passed

#1198 [Bugfix] Upload Certificate Validation Message
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed

#1195 [Cleanup] Implementation Of Notes On Client Overview Page && Little Refactoring Of Standing Component
  src/components/cards/Element.tsx
  src/pages/clients/show/components/Address.tsx
  src/pages/clients/show/components/Standing.tsx
Labels: QA passed

#1177 [Feature] Email History | Invoices | Clients
  src/common/interfaces/email-history.ts
  src/components/EmailRecord.tsx
  src/pages/clients/show/Client.tsx
  src/pages/clients/show/components/EmailHistory.tsx
  src/pages/invoices/common/components/InvoiceSlider.tsx
Labels: QA passed

#1213 Handle changing language from the user details section
  src/pages/settings/user/UserDetails.tsx
  src/pages/settings/user/components/Details.tsx
Labels: QA passed

#1199 Color schemes
  src/common/colors.ts
  src/components/layouts/Default.tsx
  src/pages/settings/user/components/Preferences.tsx
Labels: QA passed

#1219 Fixes for language resolver
  src/App.tsx
Labels: QA passed

#1216 [Bugfix] Default Tax Rates Parsing To Number
  src/pages/settings/tax-settings/components/Selector.tsx
Labels: QA passed

#1218 Dynamic triggering of live previews
  src/pages/invoices/common/components/InvoicePreview.tsx
  src/pages/invoices/common/components/InvoiceViewer.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/edit/Edit.tsx
Labels: work in progress

#1227 Fixes for client export maps
  src/common/constants/exports/client-map.ts
Labels: QA passed

#1212 add user suppression notifications
  src/common/interfaces/user.ts
  src/pages/settings/user/components/Details.tsx
  src/pages/settings/users/edit/components/Details.tsx
  tests/unit/helpers/users/user.test.ts
Labels: QA passed

#1239 Minor improvements to activity date time formats
  src/pages/dashboard/hooks/useGenerateActivityElement.tsx
Labels: QA passed

#1237 Fixes for payment labels
  src/pages/settings/online-payments/OnlinePayments.tsx
Labels: QA passed

#1236 Fixes for creating expense from a client page
  src/pages/expenses/create/Create.tsx
Labels: QA passed

#1235 Fixes for TinyMCE z-index
  src/components/forms/MarkdownEditor.tsx
Labels: QA passed

#1208 Products table: Move dnd handler to the button
  src/pages/invoices/common/components/ProductsTable.tsx
  src/pages/invoices/common/hooks/useHandleSortingRows.ts
Labels: QA passed

#1240 [Bugfix] Opening Comboboxes After Closing Modal
  src/components/forms/Combobox.tsx
Labels: QA passed

#1226 [Feature] Invoice Common Action Preferences
  src/common/hooks/useCommonActions.ts
  src/common/hooks/useReactSettings.ts
  src/common/hooks/useShowActionByPreferences.ts
  src/components/CommonActionsPreferenceModal.tsx
  src/components/SearchableSelect.tsx
  src/components/dropdown/DropdownElement.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/invoices/edit/components/Actions.tsx
  src/pages/invoices/edit/components/CommonActions.tsx
Labels: QA passed

#1245 Fixes for activity hours - display in 24hr format
  src/pages/dashboard/hooks/useGenerateActivityElement.tsx
Labels: QA passed

#1242 [Bugfix] Comobox Query Invalidation Across Whole App
  src/components/forms/Combobox.tsx
Labels: QA passed

#1233 Fixes for vendors double query
  src/common/hooks/clients/useClientResolver.ts
  src/components/forms/Combobox.tsx
  src/pages/credits/edit/Edit.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/quotes/edit/Edit.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
Labels: QA passed

#1256 Raw encoding Tiny MCE
  src/components/forms/MarkdownEditor.tsx
Labels: QA passed

#1253 Fixes for calculations
  package.json
  src/common/helpers/invoices/invoice-item-sum-inclusive.ts
  src/common/helpers/invoices/invoice-item-sum.ts
  src/pages/invoices/common/components/InvoiceTotals.tsx
  src/pages/invoices/common/hooks/useResolveTotalVariable.tsx
  src/pages/invoices/common/hooks/useTotalVariables.ts
Labels: QA passed

#1251 Updates for translations
  src/resources/lang/de/de.json
  src/resources/lang/en/en.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/fr_CA/fr_CA.json
Labels: QA passed

#1234 [Cleanup] Client Does Not Have Contact Email | Email Invoice Action
  src/pages/invoices/common/components/EmailInvoiceAction.tsx
  src/pages/invoices/common/components/SendEmailBulkAction.tsx
  src/pages/invoices/common/hooks/useCustomBulkActions.tsx
  src/pages/invoices/edit/components/Actions.tsx
Labels: QA passed

#1257 Fixes for live preview cache
  src/pages/invoices/common/components/InvoiceViewer.tsx
Labels: QA passed

#1260 Change logic for auto logout
  src/common/helpers/request.ts
Labels: QA passed

#1261 Pass UTM tracking to sign up
  src/pages/authentication/Register.tsx
Labels: QA passed

#1262 Live preview improvements
  src/pages/invoices/common/components/InvoiceViewer.tsx
Labels: QA pending

#1269 [Bugfix] New Invoice Navigation | Client Action
  src/pages/clients/common/hooks/useActions.tsx
Labels: QA passed
