Repository invoiceninja/ui, pull requests merged in 2023-12, with the labels that each got.

#1392 Move gateways to the top
  src/pages/settings/online-payments/OnlinePayments.tsx
Labels: QA passed

#1391 Adjust UI for Adding Stripe connect + PayPal
  src/pages/clients/show/components/GatewayTypeIcon.tsx
  src/pages/settings/gateways/create/Create.tsx
  src/pages/settings/gateways/create/components/gateways/PayPalPPCP.tsx
Labels: QA passed

#1389 Minor fixes for past due dates
  src/pages/dashboard/components/PastDueInvoices.tsx
  src/pages/dashboard/components/UpcomingInvoices.tsx
Labels: QA passed

#1380 Login form - autocomplete
  src/common/dtos/authentication.ts
  src/pages/authentication/Login.tsx
Labels: QA passed

#1388 [Cleanup] Task Status Action Implementation Along With Modal
  src/common/queries/task-statuses.ts
  src/components/task-statuses/TaskStatusSelector.tsx
  src/pages/tasks/create/Create.tsx
Labels: QA passed

#1385 [Feature] Credits Custom Filters
  src/pages/credits/common/hooks/useCreditsFilters.ts
  src/pages/credits/index/Credits.tsx
Labels: QA passed

#1382 [Cleanup] Additional Event Type Column | Api Webhooks
  src/pages/settings/integrations/api-webhooks/ApiWebhooks.tsx
  src/pages/settings/integrations/api-webhooks/common/hooks/useColumns.tsx
  src/pages/settings/integrations/api-webhooks/common/hooks/useEvents.ts
Labels: QA passed

#1381 [Bugfix] New Invoice | Products
  src/pages/products/common/hooks/useInvoiceProducts.ts
Labels: QA passed

#1371 [Cleanup] Adding MIssing Infinity Stale Time To Queries
  src/common/helpers/clients/client-resolver.ts
  src/common/helpers/currencies/currency-resolver.ts
  src/common/hooks/useRefetch.tsx
  src/common/hooks/vendors/useVendorResolver.ts
  src/common/queries/api-webhooks.ts
  src/common/queries/documents.ts
  src/common/queries/group-settings.ts
  src/common/queries/payment-terms.ts
  src/common/queries/projects.ts
  src/common/queries/task-statuses.ts
  src/common/queries/tax-rates.ts
  src/common/queries/users.ts
  src/components/DocumentsTable.tsx
  src/components/clients/ClientSelector.tsx
  src/components/vendors/VendorSelector.tsx
  src/pages/clients/common/components/MergeClientModal.tsx
  src/pages/dashboard/components/Activity.tsx
  src/pages/expenses/common/components/AddToInvoiceAction.tsx
  src/pages/expenses/create/components/Details.tsx
  src/pages/invoices/common/components/InvoiceSlider.tsx
  src/pages/projects/common/components/CreateProjectModal.tsx
  src/pages/projects/common/hooks.tsx
  src/pages/projects/common/hooks/useCombineProjectsTasks.ts
  src/pages/projects/create/Create.tsx
  src/pages/projects/edit/Edit.tsx
  src/pages/recurring-expenses/components/Details.tsx
  src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx
  src/pages/settings/company/documents/components/Table.tsx
  src/pages/settings/company/edit/CompanyEdit.tsx
  src/pages/settings/email-settings/EmailSettings.tsx
  src/pages/settings/group-settings/common/hooks/useActions.tsx
  src/pages/settings/schedules/common/components/EmailStatement.tsx
  src/pages/settings/system-logs/SystemLog.tsx
  src/pages/settings/tax-settings/components/Selector.tsx
  src/pages/settings/users/edit/Edit.tsx
  src/pages/tasks/common/components/AddTasksOnInvoiceAction.tsx
Labels: QA passed

#1401 Allow both onChange and onBlur selectively
  src/components/datatables/Actions.tsx
  src/components/forms/InputField.tsx
  src/pages/credits/common/components/CreditDetails.tsx
  src/pages/invoices/common/components/InvoiceDetails.tsx
  src/pages/invoices/common/hooks/useHandleProductChange.ts
  src/pages/purchase-orders/edit/components/Details.tsx
  src/pages/quotes/common/components/QuoteDetails.tsx
Labels: QA passed

#1407 Checks for NAN
  src/common/constants/blank-line-item.ts
  src/common/helpers/invoices/invoice-item-sum-inclusive.ts
  src/common/helpers/invoices/invoice-item-sum.ts
Labels: QA passed

#1405 Fixes for tests, and spot fixes for onchange/onblur
  src/components/PasswordConfirmation.tsx
  tests/e2e/client-invalidation.spec.ts
  tests/e2e/helpers.ts
Labels: QA passed

#1406 Fixes for double paypal PPCP gateway creation
  src/pages/settings/gateways/create/Create.tsx
Labels: QA passed

#1384 [Bugfix] Validation Messages For Uploading Imports
  src/components/import/UploadImport.tsx
Labels: QA passed

#1367 [Cleanup] Storing The show_mini_sidebar In React Settings
  src/common/hooks/useHandleCurrentUserChange.ts
  src/common/hooks/useReactSettings.ts
  src/common/stores/slices/settings.ts
  src/components/HelpSidebarIcons.tsx
  src/components/layouts/Default.tsx
  src/components/layouts/components/DesktopSidebar.tsx
  src/components/layouts/components/MobileSidebar.tsx
  src/components/layouts/components/SidebarItem.tsx
  src/pages/settings/user/common/hooks/useUpdateCompanyUser.ts
Labels: QA passed, pending revision

#1374 [Cleanup] Company Wizard
  src/common/interfaces/company.interface.ts
  src/pages/settings/company/components/DeleteLogo.tsx
  src/pages/settings/company/components/Logo.tsx
  src/pages/settings/company/edit/CompanyEdit.tsx
Labels: more information requested, QA passed

#1387 [Cleanup] Adjusting Designs Lists And Showing Alert Per Plan
  src/common/generic/DesignSelector.tsx
  src/common/hooks/useFreePlanDesigns.ts
  src/common/queries/designs.ts
  src/components/forms/Combobox.tsx
  src/pages/settings/invoice-design/pages/custom-designs/CustomDesigns.tsx
  src/pages/settings/invoice-design/pages/custom-designs/components/CustomDesignsPlanAlert.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/create/Create.tsx
  src/pages/settings/invoice-design/pages/general-settings/GeneralSettings.tsx
  src/pages/settings/invoice-design/pages/general-settings/components/ClientDetails.tsx
  src/pages/settings/invoice-design/pages/general-settings/components/SortableVariableList.tsx
Labels: QA passed

#1365 Improvements for dark mode compatibility across the UI
  src/App.tsx
  src/common/colors.ts
  src/components/Alert.tsx
  src/components/Breadcrumbs.tsx
  src/components/CustomField.tsx
  src/components/Modal.tsx
  src/components/Tooltip.tsx
  src/components/cards/Element.tsx
  src/components/datatables/Actions.tsx
  src/components/forms/ColorPicker.tsx
  src/components/forms/DecimalNumberInput.tsx
  src/components/forms/InputCustomField.tsx
  src/components/forms/InputField.tsx
  src/components/import/UploadImport.tsx
  src/components/layouts/components/DesktopSidebar.tsx
  src/components/layouts/components/SidebarItem.tsx
  src/pages/invoices/common/components/ProductsTable.tsx
  src/pages/payments/edit/Edit.tsx
  src/pages/payments/edit/PaymentOverview.tsx
  src/pages/payments/edit/PaymentOverviewInvoice.tsx
  src/pages/reports/common/components/ProductItemsSelector.tsx
  src/pages/reports/common/components/SortableColumns.tsx
  src/pages/reports/index/Reports.tsx
  src/pages/settings/bank-accounts/components/transaction-rules/components/TransactionRuleForm.tsx
  src/pages/settings/expense-categories/Edit.tsx
  src/pages/settings/expense-categories/components/CreateExpenseCategoryForm.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Body.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Footer.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Headers.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Includes.tsx
  src/pages/settings/templates-and-reminders/common/components/Variable.tsx
  src/pages/settings/user/components/Connect.tsx
  src/pages/tasks/common/components/TaskDetails.tsx
  src/pages/tasks/common/components/TaskStatus.tsx
  src/pages/tasks/common/components/TaskTable.tsx
  src/pages/tasks/kanban/Kanban.tsx
  src/pages/transactions/components/CreateBankAccountModal.tsx
  src/pages/transactions/components/Details.tsx
  src/pages/transactions/components/FilterModal.tsx
  src/pages/transactions/components/ListBox.tsx
  src/pages/transactions/components/ListBoxItem.tsx
  src/pages/transactions/components/SearchArea.tsx
  src/pages/transactions/components/TransactionForm.tsx
  src/pages/transactions/components/TransactionMatchDetails.tsx
Labels: QA passed

#1408 Fixes for reactivity in selected forms
  src/pages/settings/bank-accounts/components/transaction-rules/components/RuleModal.tsx
  src/pages/transactions/components/FilterModal.tsx
  src/pages/transactions/components/SearchArea.tsx
Labels: QA passed

#1412 Dark mode fixes
  src/common/helpers/number-format.ts
  src/common/hooks/credits/useCreditResolver.ts
  src/common/hooks/invoices/useInvoiceResolver.ts
  src/components/AccountWarningsModal.tsx
  src/components/Modal.tsx
  src/components/banners/VerifyPhone.tsx
  src/components/datatables/Actions.tsx
  src/pages/credits/common/components/SendEmailBulkAction.tsx
  src/pages/payments/apply/Apply.tsx
  src/pages/projects/show/Show.tsx
  src/pages/purchase-orders/edit/Edit.tsx
  src/pages/quotes/common/components/ConvertToProjectBulkAction.tsx
  src/pages/quotes/edit/Edit.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
  src/pages/reports/index/Reports.tsx
  src/pages/settings/company/create/CompanyCreate.tsx
  src/pages/settings/user/common/components/TwoFactorAuthenticationModals.tsx
  src/pages/vendors/Vendor.tsx
Labels: QA passed

#1399 [Bugfix] Displaying NaN Values
  src/common/hooks/money/useFormatMoney.ts
  src/pages/invoices/common/hooks/useFormatMoney.ts
Labels: QA passed

#1411 #1410 company switcher colors to match color mode
  src/components/CompanySwitcher.tsx
  src/components/layouts/components/DesktopSidebar.tsx
  src/components/layouts/components/MobileSidebar.tsx
Labels: QA passed

#1378 [Bugfix] Resolving Client/Vendor
  src/pages/credits/create/Create.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/purchase-orders/create/Create.tsx
  src/pages/quotes/create/Create.tsx
  src/pages/recurring-invoices/create/Create.tsx
Labels: more information requested, QA passed

#1414 Add tax rates to export maps
  src/common/constants/exports/credit-map.ts
  src/common/constants/exports/invoice-map.ts
  src/common/constants/exports/purchase-order-map.ts
  src/common/constants/exports/quote-map.ts
  src/common/constants/exports/recurring-invoice-map.ts
Labels: QA passed

#1416 [Cleanup] Showing All Invoice In Invoice Number Payment Column
  src/pages/payments/common/hooks/usePaymentColumns.tsx
Labels: QA passed

#1415 [Bugfix] Purchase Order Cloning
  src/pages/purchase-orders/edit/components/VendorSelector.tsx
Labels: QA passed

#1421 [Cleanup] Tooltip On Invoice Number Payment Column
  src/components/DynamicLink.tsx
  src/components/Tooltip.tsx
  src/components/layouts/components/DesktopSidebar.tsx
  src/pages/invoices/common/components/InvoiceSlider.tsx
  src/pages/payments/common/hooks/usePaymentColumns.tsx
Labels: QA passed

#1418 [Cleanup] Switching Company Adjustment && Adjusting Logic if User Does Not Have Dashboard Permission to Go to User Details Page
  src/App.tsx
  src/components/CompanySwitcher.tsx
  src/components/PublicRoute.tsx
  src/pages/Index.tsx
  src/pages/settings/company/create/CompanyCreate.tsx
Labels: QA passed

#1413 [Bugfix] 422 Validation 2FA Modal
  src/pages/settings/user/common/components/TwoFactorAuthenticationModals.tsx
Labels: QA passed

#1417 [Cleanup] Remove Logo CTA Implementation On All Edit Pages With PDF Preview
  src/components/RemoveLogoCTA.tsx
  src/components/forms/Link.tsx
  src/pages/credits/edit/Edit.tsx
  src/pages/invoices/common/components/InvoicePreview.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/purchase-orders/edit/Edit.tsx
  src/pages/quotes/edit/Edit.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
Labels: QA passed

#1429 updated translations
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/en_GB/en_GB.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lt/lt.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nb_NO/nb_NO.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/ru_RU/ru_RU.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sq/sq.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/th/th.json
  src/resources/lang/tr_TR/tr_TR.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#1428 Add project ID to tasks - if it exists
  src/pages/tasks/common/hooks/useInvoiceTask.ts
Labels: QA passed

#1425 [Bugfix] Products Lists For Payment Links
  src/common/queries/products.ts
  src/pages/settings/subscriptions/create/Create.tsx
  src/pages/settings/subscriptions/edit/Edit.tsx
Labels: QA passed

#1423 [Cleanup] Custom Fields Translations | Reports
  src/pages/reports/common/components/SortableColumns.tsx
Labels: QA passed

#1424 Info about app version
  src/common/helpers/version.ts
  src/components/HelpSidebarIcons.tsx
  src/pages/authentication/Login.tsx
  tsconfig.json
Labels: QA passed

#1400 [Feature] Report Schedule
  package-lock.json
  package.json
  src/common/interfaces/schedule.ts
  src/components/forms/SelectField.tsx
  src/pages/clients/common/hooks/useScheduleStatement.tsx
  src/pages/invoices/common/hooks/useScheduleEmailRecord.tsx
  src/pages/reports/common/components/ProductItemsSelector.tsx
  src/pages/reports/common/components/StatusSelector.tsx
  src/pages/reports/common/hooks/useScheduleReport.ts
  src/pages/reports/common/useReports.ts
  src/pages/reports/index/Reports.tsx
  src/pages/settings/schedules/common/components/EmailReport.tsx
  src/pages/settings/schedules/common/components/ScheduleForm.tsx
  src/pages/settings/schedules/common/hooks/useDisplayTemplateField.ts
  src/pages/settings/schedules/common/hooks/useFormatSchedulePayload.tsx
  src/pages/settings/schedules/common/hooks/useHandleChange.tsx
  src/pages/settings/schedules/common/hooks/useScheduleColumns.tsx
  src/pages/settings/schedules/common/hooks/useTemplateParametersProperties.ts
  src/pages/settings/schedules/create/Create.tsx
  src/pages/settings/schedules/edit/Edit.tsx
  tests/e2e/helpers.ts
  tests/e2e/schedule-reports.spec.ts
Labels: QA passed

#1435 [Bugfix] Bank Account Balance Formatting
  src/common/hooks/useResolveCurrency.ts
  src/pages/settings/bank-accounts/common/hooks/useBankAccountColumns.tsx
  src/pages/settings/bank-accounts/components/Details.tsx
Labels: QA passed

#1232 [Cleanup] Clone Options Refactoring
  src/common/hooks/useCommonActions.ts
  src/common/hooks/useShowActionByPreferences.ts
  src/components/CloneOption.tsx
  src/components/EntityActionElement.tsx
  src/components/Modal.tsx
  src/components/dropdown/DropdownElement.tsx
  src/components/icons/Icon.tsx
  src/pages/credits/common/components/CloneOptionsModal.tsx
  src/pages/credits/common/hooks.tsx
  src/pages/invoices/common/components/CloneOptionsModal.tsx
  src/pages/invoices/common/components/EmailInvoiceAction.tsx
  src/pages/invoices/edit/components/Actions.tsx
  src/pages/purchase-orders/common/components/CloneOptionsModal.tsx
  src/pages/purchase-orders/common/hooks.tsx
  src/pages/quotes/common/components/CloneOptionsModal.tsx
  src/pages/quotes/common/hooks.tsx
  src/pages/recurring-invoices/common/components/CloneOptionsModal.tsx
  src/pages/recurring-invoices/common/hooks.tsx
  tests/e2e/clients.spec.ts
  tests/e2e/helpers.ts
  tests/e2e/invoices.spec.ts
  tests/e2e/quotes.spec.ts
  tests/e2e/recurring-invoices.spec.ts
Labels: QA passed

#1434 [Cleanup] Blank Contact Label Adjustment
  src/pages/invoices/common/components/ClientSelector.tsx
  src/pages/purchase-orders/edit/components/VendorSelector.tsx
Labels: QA passed

#1440 [Bugfix] Translation keywords for send_email_on_mark_paid property
  src/pages/settings/online-payments/OnlinePayments.tsx
Labels: QA passed

#1438 [Bugfix] dashboard_charts props null values
  src/pages/dashboard/components/Totals.tsx
Labels: QA passed
