Repository invoiceninja/ui, pull requests merged in 2023-09, with the labels that each got.

#1082 [Cleanup] Payment Gateways Remove Duplicating Constraint && Text Field Markdown Editor
  src/pages/settings/gateways/create/Create.tsx
  src/pages/settings/gateways/create/hooks/useResolveInputField.tsx
Labels: QA passed

#1078 [Feature] Custom Bulk Actions Implementation | Recurring Expense
  src/common/queries/documents.ts
  src/common/queries/recurring-expense.ts
  src/pages/recurring-expenses/common/hooks.tsx
  src/pages/recurring-expenses/common/hooks/useCustomBulkActions.tsx
  src/pages/recurring-expenses/index/RecurringExpenses.tsx
Labels: QA passed

#1083 [Bugfix] Edit User 401 Error Handling
  src/components/DataTable.tsx
  src/pages/settings/users/edit/components/Actions.tsx
Labels: QA passed

#1088 Updated Translations
  src/pages/settings/company/documents/components/Upload.tsx
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lt/lt.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nb_NO/nb_NO.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/ru_RU/ru_RU.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sq/sq.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/th/th.json
  src/resources/lang/tr_TR/tr_TR.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#1086 [Bugfix] Missing Wepay Logo
  src/pages/settings/gateways/create/Create.tsx
Labels: QA passed

#1085 [Bugfix] Uploading Documents For Client Entity
  src/common/queries/clients.ts
  src/pages/invoices/edit/hooks/useMarkPaid.ts
  src/pages/settings/company/documents/components/Upload.tsx
Labels: QA passed

#1090 [Feature] Facebook Pixel Script/Tags Injection For Hosted Platform
  .env.example
  index.html
Labels: QA passed

#1074 Color schemes
  package-lock.json
  package.json
  src/App.tsx
  src/common/colors.ts
  src/components/Badge.tsx
  src/components/Breadcrumbs.tsx
  src/components/CompanySwitcher.tsx
  src/components/DropdownDateRangePicker.tsx
  src/components/HelpSidebarIcons.tsx
  src/components/InfoCard.tsx
  src/components/Modal.tsx
  src/components/QuickCreatePopover.tsx
  src/components/Spinner.tsx
  src/components/TabGroup.tsx
  src/components/Tabs.tsx
  src/components/cards/Card.tsx
  src/components/cards/ClickableElement.tsx
  src/components/cards/Divider.tsx
  src/components/cards/Element.tsx
  src/components/cards/NonClickableElement.tsx
  src/components/cards/Slider.tsx
  src/components/datatables/Actions.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/DropdownElement.tsx
  src/components/forms/Button.tsx
  src/components/forms/Checkbox.tsx
  src/components/forms/Combobox.tsx
  src/components/forms/DecimalNumberInput.tsx
  src/components/forms/InputField.tsx
  src/components/forms/InputLabel.tsx
  src/components/forms/MarkdownEditor.tsx
  src/components/forms/Radio.tsx
  src/components/forms/SelectField.tsx
  src/components/forms/Toggle.tsx
  src/components/layouts/Default.tsx
  src/components/layouts/Settings.tsx
  src/components/layouts/components/DesktopSidebar.tsx
  src/components/layouts/components/SidebarItem.tsx
  src/components/products/ProductSelector.tsx
  src/components/tables/Pagination.tsx
  src/components/tables/Table.tsx
  src/components/tables/Td.tsx
  src/components/tables/Th.tsx
  src/components/tables/Tr.tsx
  src/pages/authentication/Login.tsx
  src/pages/authentication/RecoverPassword.tsx
  src/pages/authentication/Register.tsx
  src/pages/authentication/components/HostedLinks.tsx
  src/pages/clients/edit/components/Contacts.tsx
  src/pages/dashboard/components/Activity.tsx
  src/pages/dashboard/components/Chart.tsx
  src/pages/dashboard/components/RecentPayments.tsx
  src/pages/dashboard/components/Totals.tsx
  src/pages/dashboard/components/UpcomingInvoices.tsx
  src/pages/dashboard/hooks/useGenerateActivityElement.tsx
  src/pages/invoices/common/components/ClientSelector.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/settings/company/components/Logo.tsx
  src/pages/settings/company/documents/components/Upload.tsx
Labels: QA pending

#1089 [Cleanup] Payment Interfaces Adjustment
  src/pages/credits/common/hooks/useApplyCredits.ts
  src/pages/invoices/common/hooks/useEnterPayment.ts
  src/pages/payments/create/Create.tsx
  src/pages/payments/create/hooks/useHandleCredit.ts
  src/pages/payments/create/hooks/useHandleInvoice.ts
  src/pages/payments/refund/Refund.tsx
Labels: QA passed

#1084 [Feature] Image Previews Implementation Across Document Tables
  src/common/hooks/useReactSettings.ts
  src/components/DocumentsTable.tsx
  src/pages/settings/user/components/Preferences.tsx
Labels: QA passed, pending revision

#1093 Import CSV hints
  src/components/import/UploadImport.tsx
Labels: QA passed

#1094 [Bugfix] Adding Additional Precision Constraint
  src/pages/expenses/create/components/AdditionalInfo.tsx
  src/pages/invoices/common/hooks/useResolveInputField.tsx
Labels: QA passed

#1098 Fixes for types for templates and reminders
  src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
Labels: QA passed

#1095 Add tasks to recurring invoices and quotes
  src/pages/quotes/common/hooks.tsx
  src/pages/quotes/create/Create.tsx
  src/pages/quotes/edit/Edit.tsx
  src/pages/recurring-invoices/common/hooks.tsx
  src/pages/recurring-invoices/create/Create.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
Labels: QA passed

#1101 Add recurring invoice `pseudo` activity
  src/common/interfaces/invoice-activity.ts
  src/pages/dashboard/hooks/useGenerateActivityElement.tsx
  src/pages/invoices/common/components/InvoiceSlider.tsx
Labels: QA passed

#1100 [Feature] Settings Public/Private | Documents
  src/common/interfaces/document.interface.ts
  src/common/queries/documents.ts
  src/components/DocumentsTable.tsx
  src/pages/settings/company/documents/components/Table.tsx
Labels: QA passed

#1099 [Feature] Gateways Prioritization for Company Settings | Implementation
  src/common/queries/company-gateways.ts
  src/pages/settings/gateways/common/components/GatewaysTable.tsx
  src/pages/settings/gateways/common/hooks/useGatewayUtilities.ts
  src/pages/settings/gateways/index/Gateways.tsx
Labels: QA passed

#1096 [Cleanup] Payment Creation Page && Combobox Selector Improvements
  src/components/forms/Combobox.tsx
  src/components/forms/InputField.tsx
  src/pages/payments/create/Create.tsx
Labels: QA passed

#1092 Combobox improvements
  src/components/forms/Combobox.tsx
  src/pages/invoices/common/hooks/useHandleProductChange.ts
Labels: pending revision

#1108 Fixes item calculations with large discounts
  src/common/helpers/invoices/invoice-item-sum-inclusive.ts
  src/common/helpers/invoices/invoice-item-sum.ts
  src/common/helpers/invoices/invoice-sum-inclusive.ts
  src/common/helpers/invoices/invoice-sum.ts
  src/common/interfaces/invoice-item.ts
  src/pages/expenses/common/useInvoiceExpense.ts
Labels: QA passed

#1110 [Cleanup] Increase Prices Action | Percent Field Changing Type To Number
  src/pages/recurring-invoices/common/components/IncreasePricesAction.tsx
Labels: QA passed

#1107 Fixes for value selection for import hinting
  src/components/import/UploadImport.tsx
Labels: QA passed

#1087 Search box
  src/common/interfaces/search.ts
  src/components/forms/Combobox.tsx
  src/components/layouts/Default.tsx
  src/pages/dashboard/components/Search.tsx
Labels: QA passed

#1116 Minor fixes for length of array check
  src/pages/clients/show/components/Gateways.tsx
Labels: QA passed

#1115 [Cleanup] Making gross_line_total and tax_amount columns readonly
  src/pages/invoices/common/hooks/useResolveInputField.tsx
Labels: QA passed

#1121 Fixes for formatting negative numbers
  src/common/helpers/number-format.ts
Labels: QA passed

#1118 [Cleanup] Vendor Contact Custom Fields Implementation
  src/pages/settings/custom-fields/vendors/Vendors.tsx
  src/pages/vendors/components/CreateVendorForm.tsx
  src/pages/vendors/create/Create.tsx
  src/pages/vendors/edit/Edit.tsx
  src/pages/vendors/edit/components/Form.tsx
Labels: QA passed

#1106 [Feature] Client Settings
  src/common/atoms/settings.ts
  src/components/layouts/Settings.tsx
  src/pages/clients/common/hooks/useActions.tsx
  src/pages/clients/common/hooks/useConfigureClientSettings.ts
  src/pages/clients/common/hooks/useUpdateClientSettings.ts
  src/pages/settings/client-portal/common/hooks/useTabs.ts
  src/pages/settings/common/hooks/useDiscardChanges.ts
  src/pages/settings/common/hooks/useHandleCompanySave.tsx
  src/pages/settings/company/common/hooks/useCompanyDetailsTabs.tsx
  src/pages/settings/company/components/Defaults.tsx
  src/pages/settings/company/components/DeleteLogo.tsx
  src/pages/settings/company/components/Logo.tsx
  src/pages/settings/gateways/index/Gateways.tsx
  src/pages/settings/group-settings/common/hooks/useConfigureGroupSettings.ts
  src/pages/settings/group-settings/common/hooks/useHandleUpdate.ts
  src/pages/settings/invoice-design/InvoiceDesign.tsx
  src/pages/settings/localization/common/hooks/useLocalizationTabs.ts
  src/pages/settings/online-payments/OnlinePayments.tsx
  src/pages/settings/task-settings/TaskSettings.tsx
  src/pages/settings/tax-settings/TaxSettings.tsx
Labels: QA passed

#1127 Improve search performance
  src/components/layouts/Default.tsx
  src/pages/dashboard/components/Search.tsx
Labels: QA passed

#1137 Invalidate invoices after payment
  src/pages/payments/apply/Apply.tsx
  src/pages/payments/create/hooks/useSave.ts
  src/pages/payments/edit/PaymentOverview.tsx
Labels: QA passed

#1136 Updated translations
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sq/sq.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/th/th.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#1135 Fixes for default task rates
  src/pages/clients/show/pages/Tasks.tsx
Labels: QA passed

#1114 [Feature] Convert To Project Single Action | Quotes | Implementation
  src/pages/quotes/common/hooks.tsx
  src/pages/quotes/common/hooks/useBulkAction.ts
Labels: QA passed, waiting for api

#1141 Fixes for in stock quantity column
  src/pages/products/common/hooks.tsx
Labels: QA passed

#1131 [Feature] Add To Inventory Single Action | Purchase Orders
  src/pages/purchase-orders/common/components/PurchaseOrderStatus.tsx
  src/pages/purchase-orders/common/hooks.tsx
Labels: QA passed

#1142 Add classification prop
  src/common/interfaces/client.ts
  src/common/interfaces/company.interface.ts
  src/common/interfaces/vendor.ts
  src/pages/clients/edit/components/Details.tsx
  src/pages/settings/company/components/Details.tsx
  src/pages/vendors/edit/components/Form.tsx
  src/resources/lang/en/en.json
Labels: QA passed

#1144 Updates for translations
  src/resources/lang/en/en.json
Labels: QA passed

#1139 [Cleanup] Product Selector Label | Track Inventory
  src/common/hooks/useResolveProduct.ts
  src/components/products/ProductSelector.tsx
  src/pages/invoices/common/hooks/useResolveInputField.tsx
  src/pages/invoices/create/hooks/useHandleCreate.ts
  src/pages/invoices/edit/hooks/useInvoiceSave.ts
Labels: QA passed

#1150 Additional props for exports
  src/common/constants/exports/client-map.ts
  src/common/constants/exports/vendor-map.ts
Labels: QA passed

#1149 [Bugfix] Property Value '0' When All Gateways Are Removed | Group & Client Settings
  src/pages/settings/gateways/common/components/GatewaysTable.tsx
  src/pages/settings/gateways/common/hooks/useGatewayUtilities.ts
Labels: QA passed

#1148 [Bugfix] Company Documents | View & Download Actions
  src/pages/settings/company/documents/components/Table.tsx
Labels: QA passed

#1147 [Bugfix] Default Tax Rates
  src/components/DataTable.tsx
  src/pages/settings/tax-rates/TaxRates.tsx
Labels: QA passed

#1145 Rework combobox
  src/common/interfaces/common-props.interface.ts
  src/components/forms/Combobox.tsx
  src/components/tables/Tr.tsx
  src/pages/invoices/common/components/ProductsTable.tsx
Labels: QA passed
