Repository invoiceninja/ui, pull requests merged in 2023-11, with the labels that each got.

#1280 logging cleanup
  src/pages/invoices/create/Create.tsx
Labels: QA passed

#1279 [Bugfix] Client Selector Not Showing For Some Permissions
  src/components/clients/ClientSelector.tsx
  src/pages/invoices/common/components/ClientSelector.tsx
Labels: QA passed

#1281 [Bugfix] Ensuring 400 erros are shown in toaster
  src/common/helpers/request.ts
  src/components/DataTable.tsx
  src/pages/settings/company/edit/CompanyEdit.tsx
  src/pages/settings/users/edit/components/Actions.tsx
Labels: QA passed

#1283 [Bugfix] Disabling Loading Google OAuth Scripts For Self-hosted
  src/components/GoogleOAuth.tsx
  src/index.tsx
  src/pages/authentication/components/SignInProviders.tsx
  src/pages/settings/user/components/Connect.tsx
Labels: QA passed

#1282 [Cleanup] Implementation Of Spinner For PDF Previews
  src/pages/clients/statement/Statement.tsx
  src/pages/invoices/common/components/InvoicePreview.tsx
  src/pages/invoices/common/components/InvoiceViewer.tsx
  src/pages/invoices/pdf/Pdf.tsx
  src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
Labels: QA passed

#1288 Localize input/output of antd rangepicker
  src/components/DropdownDateRangePicker.tsx
Labels: QA passed

#1287 Updates for invalidation rules
  src/common/hooks/useRefetch.tsx
Labels: QA passed

#1275 [Bugfix] Users Bulk Action | Password Confirmation Modal
  src/common/queries/users.ts
  src/components/DataTable.tsx
  src/components/PasswordConfirmation.tsx
  src/pages/settings/users/index/Users.tsx
Labels: QA passed, waiting on another pr

#1285 [Cleanup] Making Down Chevron On Combobox Reactive
  src/components/forms/Combobox.tsx
Labels: QA passed

#1284 Improve searchability on selectors
  src/components/CountrySelector.tsx
  src/components/CurrencySelector.tsx
Labels: QA passed

#1267 Confirmation for recurring invoices send action
  src/pages/recurring-invoices/common/components/ConfirmActionModal.tsx
  src/pages/recurring-invoices/create/Create.tsx
  src/pages/recurring-invoices/edit/Edit.tsx
Labels: QA passed

#1291 Improve cache validation after bulk actions (datatable)
  src/common/hooks/useRefetch.tsx
  src/components/DataTable.tsx
Labels: QA passed

#1298 Updates for translations
  src/resources/lang/ar/ar.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/es/es.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#1295 Add `uninvoiced` to tasks table
  src/pages/tasks/common/hooks.tsx
Labels: QA passed

#1294 Replace country selectors with searchable ones
  src/pages/clients/edit/components/address/BillingAddress.tsx
  src/pages/clients/edit/components/address/ShippingAddress.tsx
Labels: QA passed

#1293 [Bugfix] Caching Fixes For Invoice && Credit Resolver On Payment Creation Page
  src/common/helpers/credits/credit-resolver.ts
  src/common/helpers/invoices/invoice-resolver.ts
  src/common/hooks/credits/useCreditResolver.ts
  src/common/hooks/invoices/useInvoiceResolver.ts
Labels: QA passed

#1238 [Cleanup] Selecting Values After Creation Entities
  src/components/forms/Combobox.tsx
  src/pages/expenses/create/components/Details.tsx
  src/pages/invoices/common/components/TaxCreate.tsx
  src/pages/recurring-expenses/components/Details.tsx
Labels: QA passed

#1241 Delayed exports
  src/pages/reports/index/Reports.tsx
Labels: QA passed, waiting for api

#1266 Fixes for users table
  src/pages/settings/users/index/Users.tsx
Labels: QA passed, waiting for api

#1303 Fixes for address formatting
  src/pages/clients/show/components/Address.tsx
Labels: QA passed

#1302 Fixes for partial when creating a new invoice/quote etc
  src/common/helpers/invoices/invoice-sum-inclusive.ts
  src/common/helpers/invoices/invoice-sum.ts
  src/pages/invoices/common/hooks/useResolveTotalVariable.tsx
  src/pages/payments/create/Create.tsx
Labels: QA passed

#1292 Update exports to include auto bill output
  src/common/constants/exports/invoice-map.ts
  src/common/constants/exports/item-map.ts
  src/common/constants/exports/recurring-invoice-map.ts
Labels: QA passed

#1231 [Feature] Reactivate Email Action For Events In Email History
  src/common/interfaces/email-history.ts
  src/components/EmailRecord.tsx
Labels: QA passed

#1248 Changing expense category in bulk
  src/common/queries/expenses.ts
  src/pages/expenses/common/components/ExpenseCategory.tsx
  src/pages/expenses/common/hooks.tsx
  src/pages/expenses/common/hooks/useCustomBulkActions.tsx
Labels: QA passed

#1305 Add Faker
  package-lock.json
  package.json
  tests/e2e/client-invalidation.spec.ts
  tests/e2e/create-all.spec.ts
  tests/e2e/invoices.spec.ts
  tests/e2e/payments.spec.ts
  tests/e2e/projects.spec.ts
  tests/e2e/recurring-invoices.spec.ts
  tests/e2e/tasks.spec.ts
Labels: QA passed

#1307 Only present usable credits
  src/pages/payments/create/Create.tsx
Labels: QA passed

#1308 Only show discount / taxes if they exist
  src/pages/invoices/common/components/InvoiceTotals.tsx
  src/pages/invoices/common/hooks/useResolveTotalVariable.tsx
Labels: QA passed

#1315 Add Group Taxes for Quotes
  src/pages/quotes/create/Create.tsx
Labels: QA passed

#1314 [Bugfix] Statement PDF Not Displaying On Changing Parameters
  src/pages/clients/statement/Statement.tsx
Labels: QA passed

#1313 Dashboard cache improvements
  src/common/hooks/useRefetch.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/components/Totals.tsx
Labels: QA passed

#1319 [Bugfix] Overflow Issue On The Company Edit Modal && Showing Missing Toaster Error Message
  src/pages/settings/company/create/CompanyCreate.tsx
  src/pages/settings/company/edit/CompanyEdit.tsx
Labels: QA passed

#1317 [Cleanup] Sorting Lists In Alphabetical Order
  src/common/generic/DesignSelector.tsx
  src/common/queries/designs.ts
  src/common/queries/expense-categories.ts
  src/components/payment-types/PaymentTypeSelector.tsx
  src/components/tax-rates/TaxRateSelector.tsx
  src/pages/expenses/common/hooks/useCustomBulkActions.tsx
  src/pages/settings/localization/components/Settings.tsx
Labels: QA passed

#1325 Link tasks to invoices
  src/pages/tasks/common/hooks.tsx
Labels: QA passed

#1324 Add task imports
  src/pages/tasks/import/Import.tsx
  src/pages/tasks/index/Tasks.tsx
  src/pages/tasks/routes.tsx
Labels: QA passed, waiting for api

#1322 [Bugfix] Auto-opening Sliders
  src/pages/invoices/index/Invoices.tsx
  src/pages/recurring-invoices/index/RecurringInvoices.tsx
Labels: QA passed

#1320 [Bugfix] Displaying Only 'Active' Task Statuses In The Kanban
  src/pages/tasks/kanban/Kanban.tsx
Labels: QA passed

#1329 [Bugfix] Add Tasks To Invoice Bulk Action | Tasks
  src/pages/tasks/common/components/AddTasksOnInvoiceAction.tsx
Labels: QA passed

#1328 [Cleanup] Removing Client And Contact Fields Tabs From Edit Client Page && Quick UI Fix With Spacing
  src/pages/clients/edit/Edit.tsx
  src/pages/clients/edit/components/AdditionalInfo.tsx
Labels: QA passed

#1327 [Bugfix] Clone Action Spinner Bug | Products
  src/common/queries/products.ts
  src/pages/products/create/Create.tsx
Labels: QA passed

#1321 [Cleanup] Making Toggle More Visible
  src/components/forms/Toggle.tsx
Labels: QA passed

#1337 Set appropriate taxes depending on how many are configured
  src/pages/invoices/common/hooks/useResolveInputField.tsx
Labels: QA passed

#1335 Do not allow blank values for the first month of year value
  src/pages/settings/localization/components/Settings.tsx
Labels: QA passed

#1334 [Bugfix] Single Payment Query Key Definition
  src/common/queries/payments.ts
Labels: QA passed

#1333 [Bugfix] Product Fields Tab UI Fix && Additional Test To Check Correct Rendering
  src/pages/products/routes.tsx
  tests/e2e/product.spec.ts
Labels: QA passed

#1341 Updates for translations
  src/pages/invoices/common/components/ProductsTable.tsx
  src/resources/lang/en/en.json
  src/resources/lang/it/it.json
Labels: QA passed

#1339 [Bugfix] Bulk Actions Toaster Messages | Recurring Invoices
  src/pages/recurring-invoices/common/queries.ts
Labels: QA passed

#1345 [Feature] Recurring Expenses Custom Fields
  src/pages/recurring-expenses/components/Details.tsx
Labels: QA passed

#1344 [Feature] Expenses Custom Fields
  src/pages/expenses/create/components/Details.tsx
Labels: QA passed

#1343 Updates for translations and presentation of Stripe payment Methods
  src/common/constants/gateway-type.ts
  src/common/constants/payment-type.ts
  src/common/enums/gateway-type.ts
  src/resources/lang/en/en.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
Labels: QA passed

#1340 [Cleanup] Reset Text Next To X Button On Report Page
  src/pages/reports/common/components/SortableColumns.tsx
Labels: QA passed

#1323 Additional Payment settings option
  src/common/interfaces/company.interface.ts
  src/pages/settings/online-payments/OnlinePayments.tsx
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/en_GB/en_GB.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lt/lt.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nb_NO/nb_NO.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/ru_RU/ru_RU.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sq/sq.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/th/th.json
  src/resources/lang/tr_TR/tr_TR.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#1330 Revert "Revert "Add task imports""
  src/pages/tasks/import/Import.tsx
  src/pages/tasks/index/Tasks.tsx
  src/pages/tasks/routes.tsx
Labels: QA passed

#1348 Paypal PPCP gateway
  src/pages/settings/gateways/create/Create.tsx
  src/pages/settings/gateways/create/components/Credentials.tsx
  src/pages/settings/gateways/create/components/gateways/PayPalPPCP.tsx
  src/pages/settings/system-logs/SystemLog.tsx
Labels: QA passed

#1350 URL patch
  src/pages/settings/gateways/create/components/gateways/PayPalPPCP.tsx
Labels: QA passed

#1347 [Cleanup] Refactoring Of Common Actions Section | Icons Implementation
  src/components/CommonActionsPreferenceModal.tsx
  src/components/DataTable.tsx
  src/components/Tooltip.tsx
  src/components/dropdown/DropdownElement.tsx
  src/pages/invoices/common/components/EmailInvoiceAction.tsx
  src/pages/invoices/edit/components/Actions.tsx
  src/pages/invoices/edit/components/CommonActions.tsx
Labels: QA passed

#1352 [Bugfix] Columns Picker Dnd Fixes
  src/components/DataTableColumnsPicker.tsx
Labels: QA passed

#1353 [Bugfix] Add Item Text Standing Out While Dragging Items | Products Table
  src/pages/invoices/common/components/ProductsTable.tsx
Labels: QA passed

#1362 Fixes for cut and paste in clients and vendors
  src/pages/clients/edit/components/Details.tsx
  src/pages/clients/edit/components/address/BillingAddress.tsx
  src/pages/clients/edit/components/address/ShippingAddress.tsx
  src/pages/vendors/edit/components/Form.tsx
Labels: QA passed

#1358 [Cleanup] Product Selector | Clear Value Functionality
  src/pages/invoices/common/hooks/useHandleProductChange.ts
Labels: QA passed

#1369 Add staletime to client create route
  src/pages/clients/create/Create.tsx
Labels: QA passed
