Repository invoiceninja/ui, pull requests merged in 2024-02, with the labels that each got.

#1504 [Bugfix] Breadcrump URL On Quote Import Page
  src/pages/quotes/import/Import.tsx
Labels: QA passed

#1503 [Cleanup] Email History Dark Mode Adjustments
  src/components/EmailRecord.tsx
Labels: QA passed

#1502 [Cleanup] Plain "Search" Word Replaced With search Translation Keyword
  src/pages/dashboard/components/Search.tsx
Labels: QA passed

#1501 [Cleanup] Vendor Selector Made Initially Visible && Tests Adjustment
  src/components/vendors/VendorSelector.tsx
  src/pages/purchase-orders/create/Create.tsx
  src/pages/purchase-orders/edit/components/VendorSelector.tsx
  src/pages/transactions/components/SearchArea.tsx
  tests/e2e/purchase-orders.spec.ts
Labels: QA passed

#1497 [Feature] Implementation Of document_email_attachment New Report Field && Additional Tests
  src/common/interfaces/schedule.ts
  src/pages/reports/common/hooks/useScheduleReport.ts
  src/pages/reports/common/useReports.ts
  src/pages/reports/index/Reports.tsx
  src/pages/settings/schedules/common/components/EmailReport.tsx
  src/pages/settings/schedules/common/hooks/useHandleChange.tsx
  tests/e2e/schedule-reports.spec.ts
Labels: QA passed

#1496 [Feature] Implementation Of show_pdfhtml_on_mobile New Company Settings Field
  src/common/interfaces/company.interface.ts
  src/pages/settings/client-portal/components/Settings.tsx
Labels: QA passed

#1475 [Feature] New Labels For Email Provider With Additional Provider | HOSTED
  src/pages/settings/email-settings/EmailSettings.tsx
  src/pages/settings/email-settings/common/hooks/useEmailProviders.ts
Labels: QA passed

#1505 [Cleanup] Bulk Actions On Edit Company Gateway Page
  src/pages/settings/gateways/common/hooks/useActions.tsx
  src/pages/settings/gateways/edit/Edit.tsx
Labels: QA passed

#1507 [Cleanup] Vendor Split Button Implementation && Tests Adjustment
  src/pages/vendors/Vendor.tsx
  src/pages/vendors/edit/Edit.tsx
  tests/e2e/vendors.spec.ts
Labels: QA passed

#1510 [Cleanup] Purchase Order Split Button Implementation && Tests Adjustment
  src/pages/purchase-orders/edit/Edit.tsx
  tests/e2e/purchase-orders.spec.ts
Labels: QA passed

#1508 [Feature] Custom Designs Preview Action + Bulk Actions On Edit Page && Additional Tests
  src/common/queries/invoice-design.ts
  src/components/layouts/Default.tsx
  src/components/layouts/common/hooks.ts
  src/pages/invoices/common/components/InvoiceViewer.tsx
  src/pages/settings/invoice-design/common/hooks/useActions.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/Edit.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Settings.tsx
  tests/e2e/invoice-designs.spec.ts
Labels: QA passed

#1506 [Feature] Customer Stripe URL
  src/pages/clients/show/components/Gateways.tsx
Labels: QA passed

#1533 [Bugfix] Query Invalidation Issue | Kanban Task Creation
  src/common/queries/tasks.ts
Labels: QA passed

#1515 [Cleanup] Expense Edit Page Split Button && Tests Adjustment
  src/pages/expenses/Expense.tsx
  tests/e2e/expenses.spec.ts
Labels: QA passed

#1536 [Cleanup] Clearing Cache After Purging The Client
  src/pages/clients/common/hooks/usePurgeClient.ts
Labels: QA passed

#1516 [Feature] Document Counter In Tabs && Tests Adjustment
  src/common/interfaces/company.interface.ts
  src/components/DocumentsTabLabel.tsx
  src/components/TabGroup.tsx
  src/components/Tabs.tsx
  src/pages/clients/edit/components/AdditionalInfo.tsx
  src/pages/credits/common/components/CreditFooter.tsx
  src/pages/expenses/Expense.tsx
  src/pages/invoices/common/components/InvoiceFooter.tsx
  src/pages/payments/edit/hooks/useTabs.tsx
  src/pages/products/Product.tsx
  src/pages/products/common/hooks/useTabs.tsx
  src/pages/projects/Project.tsx
  src/pages/purchase-orders/edit/components/Footer.tsx
  src/pages/quotes/common/components/QuoteFooter.tsx
  src/pages/recurring-expenses/RecurringExpense.tsx
  src/pages/recurring-invoices/common/components/InvoiceFooter.tsx
  src/pages/settings/company/common/hooks/useCompanyDetailsTabs.tsx
  src/pages/settings/group-settings/edit/Edit.tsx
  src/pages/tasks/kanban/components/ViewSlider.tsx
  src/pages/vendors/Vendor.tsx
  src/pages/vendors/show/hooks/useTabs.tsx
  tests/e2e/clients.spec.ts
  tests/e2e/credits.spec.ts
  tests/e2e/expenses.spec.ts
  tests/e2e/invoices.spec.ts
  tests/e2e/payments.spec.ts
  tests/e2e/product.spec.ts
  tests/e2e/projects.spec.ts
  tests/e2e/purchase-orders.spec.ts
  tests/e2e/quotes.spec.ts
  tests/e2e/recurring-expense.spec.ts
  tests/e2e/recurring-invoices.spec.ts
  tests/e2e/vendors.spec.ts
Labels: QA passed

#1514 [Bugfix] Selecting Row When Changing The Task Status Using Dropdown On Table
  src/pages/settings/task-statuses/components/CreateTaskStatusModal.tsx
  src/pages/tasks/common/components/TaskStatus.tsx
  src/pages/tasks/common/components/TaskStatusesDropdown.tsx
Labels: QA passed

#1537 [Cleanup] From Email Missing Field Postmark/Mailgun
  src/common/interfaces/company.interface.ts
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed

#1538 [Bugfix] Trail Duration And Refund Period Changing Fields && Bulk Actions Implementation
  src/common/queries/subscriptions.ts
  src/pages/settings/subscriptions/common/components/Settings.tsx
  src/pages/settings/subscriptions/common/hooks/useActions.tsx
  src/pages/settings/subscriptions/edit/Edit.tsx
Labels: QA passed

#1540 [Bugfix] Background Color On "Yes" Button For Email Credit Bulk Action
  src/pages/credits/common/components/SendEmailBulkAction.tsx
Labels: QA passed

#1493 [Feature] Expense Report | Additional Selectors && Additional Test
  src/common/interfaces/schedule.ts
  src/common/queries/clients.ts
  src/common/queries/projects.ts
  src/common/queries/schedules.ts
  src/components/Modal.tsx
  src/pages/expenses/common/components/ExpenseCategory.tsx
  src/pages/reports/common/components/MultiClientSelector.tsx
  src/pages/reports/common/components/MultiExpenseCategorySelector.tsx
  src/pages/reports/common/components/MultiProjectSelector.tsx
  src/pages/reports/common/components/MultiVendorSelector.tsx
  src/pages/reports/common/hooks/useScheduleReport.ts
  src/pages/reports/common/hooks/useSelectorCustomStyles.ts
  src/pages/reports/common/useReports.ts
  src/pages/reports/index/Reports.tsx
  src/pages/settings/expense-categories/components/CreateExpenseCategoryModal.tsx
  src/pages/settings/schedules/common/components/EmailReport.tsx
  src/pages/settings/schedules/common/hooks/useActions.tsx
  src/pages/settings/schedules/common/hooks/useFormatSchedulePayload.tsx
  src/pages/settings/schedules/common/hooks/useHandleChange.tsx
  src/pages/settings/schedules/edit/Edit.tsx
  tests/e2e/reports.spec.ts
  tests/e2e/schedule-reports.spec.ts
Labels: QA passed

#1543 [Bugfix] Classification Field Validation
  src/pages/vendors/edit/components/Form.tsx
Labels: QA passed

#1534 [Bugfix] Expenses/Recurring Expenses Amount Calculation
  src/common/interfaces/company.interface.ts
  src/pages/expenses/common/hooks.tsx
  src/pages/expenses/common/hooks/useCalculateExpenseAmount.ts
  src/pages/expenses/create/Create.tsx
  src/pages/expenses/create/components/AdditionalInfo.tsx
  src/pages/expenses/create/components/Details.tsx
  src/pages/expenses/create/components/Taxes.tsx
  src/pages/recurring-expenses/common/hooks.tsx
  src/pages/recurring-expenses/components/AdditionalInfo.tsx
  src/pages/recurring-expenses/components/Details.tsx
  src/pages/recurring-expenses/components/Taxes.tsx
  src/pages/recurring-expenses/create/Create.tsx
  src/pages/settings/expense-settings/ExpenseSettings.tsx
  src/pages/settings/tax-settings/TaxSettings.tsx
  tests/e2e/expenses.spec.ts
  tests/e2e/recurring-expense.spec.ts
  tests/e2e/taxes-helpers.ts
Labels: QA passed

#1546 [Cleanup] Custom Templates Labels && Test Adjustment
  src/pages/invoices/common/components/SendEmailModal.tsx
  src/pages/invoices/email/components/Mailer.tsx
  tests/e2e/invoices.spec.ts
Labels: QA passed

#1539 [Bugfix] Adding Permission On new_expense_category Action In Dropdown On Category Status Badge && Additional Tests
  src/common/queries/expense-categories.ts
  src/components/DataTableColumnsPicker.tsx
  src/components/dropdown/DropdownElement.tsx
  src/components/expense-categories/ExpenseCategorySelector.tsx
  src/pages/expenses/common/components/ExpenseCategory.tsx
  tests/e2e/expenses.spec.ts
Labels: QA passed

#1545 [Cleanup] Adding Missing Classification Options For Client/Vendor/Company
  src/pages/clients/edit/components/Details.tsx
  src/pages/settings/company/components/Details.tsx
  src/pages/vendors/edit/components/Form.tsx
Labels: QA passed

#1542 [Feature] Quote Slider
  src/common/interfaces/quote-activity.ts
  src/components/CloneOption.tsx
  src/pages/credits/common/components/CloneOptionsModal.tsx
  src/pages/invoices/common/components/CloneOptionsModal.tsx
  src/pages/purchase-orders/common/components/CloneOptionsModal.tsx
  src/pages/quotes/common/components/CloneOptionsModal.tsx
  src/pages/quotes/common/components/QuoteSlider.tsx
  src/pages/quotes/common/components/QuoteStatus.tsx
  src/pages/quotes/common/hooks.tsx
  src/pages/quotes/index/Quotes.tsx
  src/pages/recurring-invoices/common/components/CloneOptionsModal.tsx
Labels: QA passed, pending revision

#1544 [Cleanup] Adjusting Logic For Manipulation With Line Items Without Selecting Client/Vendor
  src/common/helpers/country/country-resolver.ts
  src/pages/invoices/common/components/ProductsTable.tsx
  src/pages/invoices/common/hooks/useFormatMoney.ts
  src/pages/invoices/common/hooks/useResolveInputField.tsx
Labels: more information requested, QA passed

#1549 [Feature] Payment Slider
  src/common/interfaces/payment-activity.ts
  src/common/queries/payments.ts
  src/pages/payments/common/components/PaymentSlider.tsx
  src/pages/payments/common/hooks/useActions.tsx
  src/pages/payments/index/Payments.tsx
Labels: QA passed

#1567 [Bugfix] Pagination On Clients Table On Edit Group Settings Page && Formatting Code On Client Actions
  src/pages/clients/common/components/MergeClientAction.tsx
  src/pages/clients/common/components/PurgeClientAction.tsx
  src/pages/clients/common/hooks/useActions.tsx
  src/pages/clients/common/hooks/usePurgeClient.ts
  src/pages/clients/edit/Edit.tsx
  src/pages/clients/index/Clients.tsx
  src/pages/clients/show/Client.tsx
  src/pages/settings/group-settings/edit/components/Clients.tsx
Labels: QA passed

#1569 Updated translations
  src/resources/lang/ar/ar.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/en/en.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lo_LA/lo_LA.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#1568 [Feature] New Company Settings Field "use_unapplied_payment"
  src/common/interfaces/company.interface.ts
  src/pages/settings/online-payments/OnlinePayments.tsx
Labels: QA passed

#1554 [Feature] Task Slider
  src/common/interfaces/task-activity.ts
  src/pages/tasks/common/components/TaskSlider.tsx
  src/pages/tasks/common/hooks.tsx
  src/pages/tasks/index/Tasks.tsx
Labels: QA passed

#1572 [Bugfix] Custom Select Field Values
  src/components/forms/InputCustomField.tsx
Labels: QA passed

#1576 [Bugfix] Purchase Order Custom Fields Labels | Invoice Design
  src/pages/settings/invoice-design/pages/general-settings/components/PurchaseOrderDetails.tsx
Labels: QA passed

#1577 [Cleanup] Client/Vendor Column Hidding On Client and Vendor Show Page
  src/components/DataTable.tsx
  src/pages/clients/show/pages/Credits.tsx
  src/pages/clients/show/pages/Expenses.tsx
  src/pages/clients/show/pages/Invoices.tsx
  src/pages/clients/show/pages/Payments.tsx
  src/pages/clients/show/pages/Projects.tsx
  src/pages/clients/show/pages/Quotes.tsx
  src/pages/clients/show/pages/RecurringExpenses.tsx
  src/pages/clients/show/pages/RecurringInvoices.tsx
  src/pages/clients/show/pages/Tasks.tsx
  src/pages/vendors/show/pages/Expenses.tsx
  src/pages/vendors/show/pages/PurchaseOrders.tsx
  src/pages/vendors/show/pages/RecurringExpenses.tsx
Labels: QA passed

#1575 [Bugfix] Transaction Description
  src/pages/transactions/common/hooks/useCleanDescription.ts
  src/pages/transactions/common/hooks/useTransactionColumns.tsx
  src/pages/transactions/edit/Edit.tsx
Labels: QA passed

#1574 [Feature] Displaying Gross Amount | Expenses| Recurring Expenses
  src/pages/expenses/create/components/Details.tsx
  src/pages/recurring-expenses/components/Details.tsx
Labels: QA passed

#1571 [Cleanup] Implementation Of Color Picker Button
  src/components/forms/ColorPicker.tsx
Labels: QA passed

#1579 [Feature] API Version On Health Check Modal
  src/components/AboutModal.tsx
Labels: QA passed

#1582 [Bugfix] SMTP Selection Bug && Hidding Option On Demo
  src/pages/settings/email-settings/common/components/SMTPMailDriver.tsx
  src/pages/settings/email-settings/common/hooks/useEmailProviders.ts
Labels: QA passed

#1580 [Bugfix] Duplicating Company Gateways
  src/pages/settings/gateways/common/hooks/useGatewayUtilities.ts
Labels: QA passed
