Repository invoiceninja/ui, pull requests merged in 2024-06, with the labels that each got.

#1795 [Cleanup] Changing Tooltip "reconnect_account" Keyword
  src/pages/settings/bank-accounts/common/hooks/useBankAccountColumns.tsx
Labels: QA passed

#1786 [Cleanup] Refactoring Client Show Page
  src/common/queries/clients.ts
  src/pages/clients/show/Client.tsx
  src/pages/clients/show/components/Address.tsx
  src/pages/clients/show/components/ClientPrivateNotes.tsx
  src/pages/clients/show/components/ClientPublicNotes.tsx
  src/pages/clients/show/components/Contacts.tsx
  src/pages/clients/show/components/Details.tsx
  src/pages/clients/show/components/EmailHistory.tsx
  src/pages/clients/show/components/Gateways.tsx
  src/pages/clients/show/components/Standing.tsx
  src/pages/clients/show/pages/Activities.tsx
Labels: QA passed

#1794 [Cleanup] Implementing CTAs For Vendor Selector
  src/pages/purchase-orders/edit/components/VendorSelector.tsx
Labels: QA passed

#1793 Fixes for recurring invoice activity
  src/common/interfaces/recurring-invoice-activity.ts
  src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx
Labels: QA passed

#1796 [Cleanup] Implementing Reduced Concept For Vendor Modal
  src/pages/vendors/components/CreateVendorForm.tsx
  src/pages/vendors/components/CreateVendorModal.tsx
  src/pages/vendors/edit/components/Form.tsx
Labels: QA passed

#1797 Add back iZettle
  src/common/constants/payment-type.ts
  src/common/enums/payment-type.ts
Labels: QA passed, hot patch

#1785 [Feature] Implementing "Entity Type" and "Entity Id" Selectors | Custom Designs
  src/components/credit/CreditSelector.tsx
  src/components/invoices/InvoiceSelector.tsx
  src/components/purchase-order/PurchaseOrderSelector.tsx
  src/components/quotes/QuoteSelector.tsx
  src/pages/settings/invoice-design/pages/custom-designs/CustomDesign.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Settings.tsx
Labels: QA passed

#1800 [Bugfix] Fixing Versions Data Source
  src/components/AboutModal.tsx
Labels: QA passed

#1803 [Cleanup] Implementing Client CTAs Consistent
  src/common/queries/projects.ts
  src/pages/clients/show/components/ClientCard.tsx
  src/pages/expenses/create/components/Details.tsx
  src/pages/invoices/common/components/ClientActionButtons.tsx
  src/pages/invoices/common/components/ClientSelector.tsx
  src/pages/projects/edit/Edit.tsx
  src/pages/projects/show/Show.tsx
  src/pages/recurring-expenses/components/Details.tsx
  src/pages/tasks/common/components/TaskDetails.tsx
Labels: QA passed

#1801 [Cleanup] Cleaning up Payment Terms Pages
  src/components/layouts/common/hooks.ts
  src/pages/settings/payment-terms/Create.tsx
  src/pages/settings/payment-terms/PaymentTerms.tsx
  src/pages/settings/payment-terms/edit/Edit.tsx
Labels: QA passed

#1802 [Feature] New Lock Invoices Option
  src/pages/settings/workflow-settings/components/Invoices.tsx
Labels: QA passed

#1805 [Cleanup] Group Settings Plan Alert Banner
  src/pages/settings/group-settings/create/Create.tsx
Labels: QA passed

#1807 [Cleanup] Replacing "Cancel" Invoice Action
  src/components/DataTable.tsx
  src/pages/clients/index/Clients.tsx
  src/pages/invoices/edit/components/Actions.tsx
  src/pages/invoices/index/Invoices.tsx
  src/pages/settings/group-settings/edit/components/Clients.tsx
Labels: QA passed

#1808 Set twig as default language for custom designs
  src/pages/invoices/common/components/InvoiceViewer.tsx
  src/pages/settings/invoice-design/pages/custom-designs/CustomDesign.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Body.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Footer.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Headers.tsx
  src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Includes.tsx
Labels: QA passed

#1809 [Cleanup] Implementing 'Group' Column and Adjusting Show Page | Clients
  src/pages/clients/common/hooks/useClientColumns.tsx
  src/pages/clients/index/Clients.tsx
  src/pages/clients/show/components/Details.tsx
  src/pages/settings/group-settings/edit/components/Clients.tsx
Labels: QA passed

#1812 [Cleanup] Adjusting "Expires On" Label | Account Management
  src/pages/settings/account-management/component/Plan.tsx
Labels: QA passed

#1821 [Bugfix] Wrapping Words In The Dropdown | Different Languages
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/DropdownElement.tsx
Labels: QA passed

#1815 [Cleanup] Adding "City" Column For Clients
  src/components/DataTableColumnsPicker.tsx
  src/pages/clients/common/hooks/useClientColumns.tsx
Labels: QA passed

#1824 [Bugfix] Adding Missing Fields "Replay to Email/Name" | Smtp Configuration
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed

#1820 [Bugfix] Task Time Log Start Date
  src/pages/tasks/common/components/TaskTable.tsx
  src/pages/tasks/common/helpers.ts
  src/pages/tasks/kanban/components/EditSlider.tsx
Labels: QA passed

#1825 [Bugfix] Adjusting Dark Mode For Some Selectors
  src/pages/reports/common/components/ProductItemsSelector.tsx
  src/pages/reports/common/components/StatusSelector.tsx
  src/pages/settings/gateways/common/components/GatewaysTable.tsx
Labels: QA passed

#1827 [Bugfix] Enabling "Health Check" Endpoint Only On Self-Hosted
  src/components/AboutModal.tsx
Labels: QA passed

#1817 [Bugfix] "Cancel" Action Order
  src/pages/invoices/edit/components/Actions.tsx
Labels: QA passed

#1814 [Bugfix] Mapping Custom Values | Add To Invoice Action | Tasks
  src/pages/tasks/common/hooks/useAddTasksOnInvoice.ts
  src/pages/tasks/common/hooks/useInvoiceTask.ts
Labels: QA passed

#1823 [Bugfix] Disabling "Portal Mode" | Client Portal
  src/pages/settings/client-portal/components/Settings.tsx
Labels: QA passed

#1828 [Cleanup] Implementing Tooltip For Copy Portal URL Icon
  src/pages/invoices/common/components/ClientSelector.tsx
Labels: QA passed

#1833 [Bugfix] Rappen Rounding Translation
  src/pages/settings/localization/components/Settings.tsx
Labels: QA passed

#1834 [Bugfix] Company Wizard Logo && Navigation
  src/pages/settings/company/edit/CompanyEdit.tsx
Labels: QA passed

#1835 Disable TinyMCE auto link convert
  src/components/forms/MarkdownEditor.tsx
Labels: QA pending

#1836 [Bugfix] Company Wizard Paypal URL
  src/pages/settings/company/edit/CompanyEdit.tsx
Labels: QA passed

#1837 [Cleanup] "Balance" Column Adjusting | Recurring Invoices | Dashboard
  src/pages/dashboard/components/UpcomingRecurringInvoices.tsx
Labels: QA passed

#1838 Settings: Merge e-invoice to PDF
  src/common/interfaces/company.interface.ts
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed

#1840 [Cleanup] Removing "All" Filter | Custom Filters
  src/common/hooks/useDataTablePreferences.ts
  src/common/hooks/useDataTableUtilities.ts
  src/pages/clients/show/hooks/useDocumentFilters.ts
  src/pages/credits/common/hooks/useCreditsFilters.ts
  src/pages/expenses/common/hooks.tsx
  src/pages/invoices/common/hooks/useInvoiceFilters.ts
  src/pages/payments/common/hooks/usePaymentFilters.tsx
  src/pages/purchase-orders/common/hooks.tsx
  src/pages/quotes/common/hooks.tsx
  src/pages/recurring-invoices/common/hooks.tsx
  src/pages/tasks/common/hooks.tsx
  src/pages/transactions/common/hooks/useTransactionFilters.tsx
Labels: QA passed

#1829 [Bugfix] Encoding CSV Files
  src/components/import/UploadImport.tsx
Labels: QA passed

#1845 [Feature] Adding "BTCPay" Logo | Gateways
  public/gateway-card-images/btcpay.png
  src/pages/clients/show/components/GatewayTypeIcon.tsx
  src/pages/clients/show/components/Gateways.tsx
  src/pages/settings/gateways/create/Create.tsx
Labels: QA passed

#1858 [Bugfix] "Per Page" Query Parameter | Dashboard Tables
  src/common/hooks/useDataTablePreferences.ts
  src/components/DataTable.tsx
  src/pages/dashboard/components/ExpiredQuotes.tsx
  src/pages/dashboard/components/PastDueInvoices.tsx
  src/pages/dashboard/components/RecentPayments.tsx
  src/pages/dashboard/components/UpcomingInvoices.tsx
  src/pages/dashboard/components/UpcomingQuotes.tsx
  src/pages/dashboard/components/UpcomingRecurringInvoices.tsx
Labels: QA passed

#1862 [Bugfix] Time Logs Parsing | Format Date Issue
  src/common/helpers.ts
  src/pages/tasks/kanban/common/hooks.ts
Labels: QA pending

#1859 [Bugfix] Query Invalidation | Add Task To Invoice
  src/pages/invoices/edit/hooks/useInvoiceSave.ts
Labels: QA passed

#1865 [Bugfix] Hours Calculation When Task Running | Amount Money Formatting
  src/pages/projects/common/hooks/useInvoiceProject.tsx
Labels: QA passed

#1863 [Cleanup] Hiding "Copy to Clipboard" Icon When Context Is Not Secure
  src/components/CopyToClipboard.tsx
Labels: QA passed

#1853 [Bugfix] Chart Data Fixes
  src/components/AboutModal.tsx
  src/pages/dashboard/components/Chart.tsx
  src/pages/dashboard/hooks/useGenerateWeekDateRange.ts
Labels: QA passed

#1864 Group tasks into two groups
  src/pages/tasks/common/components/TaskDetails.tsx
Labels: QA passed

#1867 [Feature] Implementing Task Assigned Toggle | Notifications | User Details
  src/pages/settings/user/components/Notifications.tsx
Labels: QA passed
