Repository invoiceninja/ui, pull requests merged in 2024-09, with the labels that each got.

#2004 New payment flow: settings
  src/common/interfaces/company.interface.ts
  src/pages/settings/online-payments/OnlinePayments.tsx
Labels: pending merge

#2017 [Feature] New Email Template | Payment Failed
  src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
Labels: QA passed

#2019 [Feature] Implementing Date Range Picker
  src/pages/credits/common/hooks.tsx
  src/pages/credits/common/hooks/useDateRangeColumns.ts
  src/pages/credits/index/Credits.tsx
  src/pages/purchase-orders/common/hooks/useDateRangeColumns.ts
  src/pages/purchase-orders/index/PurchaseOrders.tsx
  src/pages/quotes/common/hooks/useDateRangeColumns.ts
  src/pages/quotes/index/Quotes.tsx
Labels: QA passed

#2013 [Bugfix] Prevent Navigation Modal Fixes
  .env.example
  package-lock.json
  package.json
  src/common/hooks/useAtomWithPrevent.ts
  src/components/EntityActionElement.tsx
  src/components/PreventNavigationModal.tsx
  src/components/dropdown/DropdownElement.tsx
  src/pages/invoices/Invoice.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/create/hooks/useInvoiceUtilities.ts
  src/pages/quotes/Quote.tsx
  src/pages/quotes/common/components/ConvertToProjectBulkAction.tsx
  src/pages/quotes/common/hooks.tsx
  src/pages/quotes/create/Create.tsx
Labels: QA passed

#2020 [Bugfix] Taxes Applying When Cloning
  src/pages/invoices/create/Create.tsx
  src/pages/quotes/create/Create.tsx
Labels: QA passed

#2024 [Bugfix] Reseting "Reset Counter Date"
  src/pages/settings/generated-numbers/components/Settings.tsx
Labels: QA passed

#2025 [Bugfix] Displaying "Force Update" Button
  src/components/AboutModal.tsx
Labels: QA passed

#2026 [Bugfix] Displaying Validation Error Message | Payments | Refund
  src/pages/payments/refund/Refund.tsx
Labels: QA passed

#2027 [Cleanup] Displaying "Processing" Modal On self-update
  src/components/AboutModal.tsx
Labels: QA passed

#2028 Update for invoice sent label
  src/pages/settings/user/common/hooks/useNotificationOptions.ts
Labels: QA passed

#2029 [Cleanup] Changing Toaster Message While Emailing
  src/common/hooks/emails/useHandleSend.ts
Labels: QA passed

#2030 [Bugfix] Avoiding NaN Values For Task Duration
  src/pages/tasks/common/helpers/calculate-time.ts
Labels: QA passed

#2042 [Bugfix] Selecting "view_dashboard" && "view_reports" Permissions
  src/pages/settings/users/edit/components/Permissions.tsx
Labels: QA passed

#2039 [Bugfix] Overriding Taxes
  src/pages/credits/create/Create.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/quotes/create/Create.tsx
  src/pages/recurring-invoices/create/Create.tsx
  src/pages/settings/tax-settings/components/Selector.tsx
Labels: QA passed

#2045 [Bugfix] Client Tax Exempt Overriding
  src/pages/credits/create/Create.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/quotes/create/Create.tsx
  src/pages/recurring-invoices/create/Create.tsx
Labels: QA passed

#2046 [Cleanup] Slack Icon As Contact Link For Self-Hosted
  src/components/HelpSidebarIcons.tsx
Labels: QA passed

#2049 [Bugfix] Implementing 3 Missing Invalidations
  src/common/queries/purchase-orders.ts
  src/pages/quotes/common/hooks/useBulkAction.ts
Labels: QA passed

#2050 ES autonomous regions
  src/common/constants/eu-countries.ts
Labels: QA passed

#2052 [Bugfix] Selecting Multi Line Text Custom Field
  src/pages/settings/custom-fields/components/Field.tsx
Labels: QA passed

#2055 [Cleanup] Replacing Dropdowns With Searchable Dropdowns
  src/components/EUCountrySelector.tsx
  src/components/USStateSelector.tsx
  src/pages/settings/company/components/Address.tsx
Labels: QA passed

#2056 [Bugfix] Scrolling App Issue
  src/components/import/ImportTemplateModal.tsx
Labels: QA passed

#1940 POC Websockets.
  .env.example
  package-lock.json
  package.json
  src/App.tsx
  src/common/hooks/useSockets.ts
  src/common/queries/sockets.ts
  src/components/Notifications.tsx
  src/components/layouts/Default.tsx
  src/env.d.ts
  src/index.tsx
  src/pages/dashboard/components/Search.tsx
  src/pages/invoices/Invoice.tsx
  src/pages/invoices/index/Invoices.tsx
Labels: QA passed

#2061 [Cleanup] Project Query On Tasks
  src/common/queries/clients.ts
  src/components/projects/ProjectSelector.tsx
  src/pages/tasks/common/components/TaskDetails.tsx
Labels: QA passed

#2063 [Bugfix] Language-Searchable Selector Does Not Overflowing TinyMCE
  src/components/SearchableSelect.tsx
Labels: QA passed

#2064 [Bugfix] Invoicing Project Does Not Apply Project Id To An Invoice
  src/pages/projects/common/hooks.tsx
  src/pages/projects/common/hooks/useInvoiceProject.tsx
Labels: QA passed

#2065 [Cleanup] Displaying Project Link On Invoice Edit Page
  src/components/Assigned.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/tasks/common/hooks.tsx
Labels: QA passed

#2054 [Bugfix] Displaying Modal With Message When Invoice Is Locked
  src/common/interfaces/invoice.ts
  src/common/queries/invoices.ts
  src/components/ResourceActions.tsx
  src/pages/invoices/Invoice.tsx
Labels: QA passed

#2059 [Cleanup] Import Template Keys
  src/common/hooks/useReactSettings.ts
  src/components/import/ImportTemplateModal.tsx
  src/components/import/UploadImport.tsx
Labels: QA passed

#2051 [Cleanup] Implementing "View Portal" Action On Contacts Card | Client Overview Page
  src/components/CopyToClipBoardIconOnly.tsx
  src/components/Tooltip.tsx
  src/pages/clients/common/hooks/useActions.tsx
  src/pages/clients/show/components/Contacts.tsx
Labels: QA passed

#2067 Search: Pinging server
  src/pages/dashboard/components/Search.tsx
Labels: QA passed

#1819 GoCardless OAuth2
  src/pages/settings/gateways/create/Create.tsx
  src/pages/settings/gateways/create/components/Credentials.tsx
  src/pages/settings/gateways/create/components/gateways/GoCardlessOAuth2.tsx
  src/pages/settings/gateways/create/hooks/useHandleGoCardless.ts
Labels: QA passed

#2071 Table: Update actions label
  src/components/DataTable.tsx
  src/components/DocumentsTable.tsx
  src/pages/settings/company/documents/components/Table.tsx
Labels: QA passed

#2073 [Cleanup] Changing Behavior For Client Selector | Task Pages
  src/pages/tasks/common/components/TaskDetails.tsx
Labels: QA passed

#2068 Help widget
  package-lock.json
  package.json
  src/components/HelpWidget.tsx
  src/components/import/UploadImport.tsx
  src/pages/clients/import/Import.tsx
  src/pages/invoices/import/Import.tsx
  src/pages/products/import/Import.tsx
  src/pages/quotes/import/Import.tsx
  src/pages/recurring-invoices/import/Import.tsx
  src/pages/tasks/import/Import.tsx
  src/pages/transactions/import/Import.tsx
  src/pages/vendors/import/Import.tsx
Labels: QA pending

#2078 Updated translations
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/en_GB/en_GB.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lo_LA/lo_LA.json
  src/resources/lang/lt/lt.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nb_NO/nb_NO.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/ru_RU/ru_RU.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sq/sq.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/th/th.json
  src/resources/lang/tr_TR/tr_TR.json
  src/resources/lang/vi/vi.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed
