Repository invoiceninja/ui, pull requests merged in 2024-11, with the labels that each got.

#2161 Updated translations
  src/resources/lang/ar/ar.json
  src/resources/lang/de/de.json
  src/resources/lang/en/en.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/he/he.json
  src/resources/lang/nl/nl.json
  src/resources/lang/vi/vi.json
Labels: QA passed

#2160 Remove invoice reversal option
  src/pages/invoices/common/hooks/useCustomBulkActions.tsx
  src/pages/invoices/edit/components/Actions.tsx
Labels: QA passed

#2159 GoCardless: Remove debugging statements
  src/pages/settings/gateways/create/Create.tsx
  src/pages/settings/gateways/create/components/Credentials.tsx
Labels: QA passed

#2166 E-invoicing: Add connection status & legal entity id
  src/components/e-invoice/PaymentMeans.tsx
  src/pages/settings/e-invoice/peppol/Preferences.tsx
Labels: QA passed

#2168 [Bugfix] E-Invoice Types Selector Issue Fix
  src/pages/settings/e-invoice/EInvoice.tsx
Labels: QA passed

#2164 E-invoicing: Remove message about payment means
  src/components/e-invoice/PaymentMeans.tsx
Labels: QA passed

#2165 E-invoicing: Add message about company details being updated
  src/pages/settings/e-invoice/peppol/Onboarding.tsx
Labels: QA passed

#2172 [Cleanup] Adding Helper Text For Gateways
  src/pages/settings/gateways/create/components/LimitsAndFees.tsx
  src/pages/settings/gateways/create/components/Settings.tsx
  src/pages/settings/gateways/create/hooks/useResolveGatewayTypeTranslation.ts
Labels: pending merge

#2173 [Cleanup] Changing Translation To "Tokenize"
  src/pages/settings/gateways/create/components/Settings.tsx
Labels: pending merge

#2174 [Cleanup] Importing "location" From react-router-dom Pacakge
  src/pages/credits/edit/components/Documents.tsx
  src/pages/invoices/edit/components/Documents.tsx
  src/pages/purchase-orders/edit/components/Documents.tsx
  src/pages/quotes/edit/components/Documents.tsx
  src/pages/recurring-invoices/edit/components/Documents.tsx
Labels: QA passed

#2179 [Cleanup] Adding "First Reminder" When Emailing Quote
  src/pages/quotes/email/Email.tsx
Labels: QA passed

#2163 eInvoicing
  src/common/guards/guards/white-label.ts
  src/common/helpers/peppol-countries.ts
  src/common/hooks/usePaidOrSelfhost.ts
  src/common/interfaces/client.ts
  src/common/interfaces/company.interface.ts
  src/components/e-invoice/EInvoiceGenerator.tsx
  src/components/e-invoice/PaymentMeans.tsx
  src/components/forms/Button.tsx
  src/components/forms/SelectField.tsx
  src/components/layouts/Settings.tsx
  src/pages/clients/common/hooks/useConfigureClientSettings.ts
  src/pages/clients/common/hooks/useUpdateClientSettings.ts
  src/pages/invoices/Invoice.tsx
  src/pages/invoices/common/hooks/useTabs.tsx
  src/pages/invoices/edit/components/EInvoice.tsx
  src/pages/invoices/routes.tsx
  src/pages/settings/company/components/Details.tsx
  src/pages/settings/e-invoice/EInvoice.tsx
  src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
  src/pages/settings/e-invoice/common/components/ValidationAlert.tsx
  src/pages/settings/e-invoice/common/hooks/useCheckEInvoiceValidation.ts
  src/pages/settings/e-invoice/peppol/Onboarding.tsx
  src/pages/settings/e-invoice/peppol/Preferences.tsx
  src/resources/e-invoice/peppol/peppol.json
  src/resources/lang/ar/ar.json
  src/resources/lang/ca/ca.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/en/en.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lo_LA/lo_LA.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sv/sv.json
  src/resources/lang/vi/vi.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA pending, work in progress

#2183 E-invocing: Adjust purchase links
  src/common/interfaces/statics.ts
  src/pages/settings/e-invoice/peppol/Preferences.tsx
Labels: QA passed

#2184 [Cleanup] Hiding E-Invoice Card When PEPPOL Is Enabled
  src/pages/settings/e-invoice/EInvoice.tsx
Labels: QA passed

#2187 [Bugfix] Making Helper Text Visible Only For Stripe
  src/pages/settings/gateways/create/components/Settings.tsx
Labels: QA passed

#2185 [Cleanup] Making Payment Means Form Available For All E-Invoice Types
  src/components/e-invoice/PaymentMeans.tsx
  src/pages/settings/e-invoice/EInvoice.tsx
Labels: QA passed

#2189 E-invoices: Few improvements
  src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
  src/pages/settings/e-invoice/peppol/Onboarding.tsx
Labels: QA passed

#2191 E-invoicing: Remove invalid company alert
  src/pages/settings/e-invoice/EInvoice.tsx
  src/pages/settings/e-invoice/common/components/ValidationAlert.tsx
  src/pages/settings/e-invoice/common/hooks/useCheckEInvoiceValidation.ts
Labels: QA passed

#2190 E-invoicing: Banners for low credits
  src/components/Banner.tsx
  src/components/banners/EInvoiceCredits.tsx
  src/components/layouts/Default.tsx
  src/pages/settings/e-invoice/peppol/Preferences.tsx
Labels: QA passed

#2194 E-invoicing: Improve validation
  src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
Labels: QA passed

#2188 [Feature] Implementing "Quick Actions" | Credits
  src/common/hooks/useCommonActions.ts
  src/components/CommonActionsPreferenceModal.tsx
  src/pages/credits/Credit.tsx
  src/pages/credits/common/components/CloneOptionsModal.tsx
  src/pages/credits/common/hooks.tsx
  src/pages/invoices/Invoice.tsx
  src/pages/invoices/edit/components/CommonActions.tsx
Labels: QA passed

#2200 E-invoicing: Fixes & improvements
  .env.example
  src/common/helpers/request.ts
  src/components/banners/EInvoiceCredits.tsx
  src/env.d.ts
  src/pages/settings/e-invoice/EInvoice.tsx
  src/pages/settings/e-invoice/peppol/Preferences.tsx
Labels: QA passed

#2186 [Cleanup] E-Invoice Entity Validation | Invoice Edit Page
  src/common/hooks/useRefetch.tsx
  src/pages/invoices/Invoice.tsx
  src/pages/invoices/common/hooks/useTabs.tsx
  src/pages/invoices/edit/components/EInvoice.tsx
  src/pages/invoices/edit/components/InvoiceEntityValidationButton.tsx
  src/pages/settings/common/hooks/useHandleCompanySave.tsx
  src/pages/settings/e-invoice/EInvoice.tsx
  src/pages/settings/e-invoice/common/components/ValidationAlert.tsx
  src/pages/settings/e-invoice/common/hooks/useCheckEInvoiceValidation.ts
Labels: QA passed

#2203 [Bugfix] External Links Path Issue
  src/components/forms/Link.tsx
Labels: QA passed

#2201 [Feature] New Reports/Schedule "Attach PDF" Toggle Field
  src/common/interfaces/schedule.ts
  src/pages/reports/common/hooks/useScheduleReport.ts
  src/pages/reports/common/hooks/useShowReportField.ts
  src/pages/reports/common/useReports.ts
  src/pages/reports/index/Reports.tsx
  src/pages/settings/schedules/common/components/EmailReport.tsx
  src/pages/settings/schedules/common/hooks/useHandleChange.tsx
Labels: QA passed

#2208 [Bugfix] Adjusting Client Portal Link
  src/pages/invoices/common/helpers/open-client-portal.ts
Labels: QA passed

#2206 E-invoicing: Hide current country
  src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
Labels: QA passed

#2212 E-invoicing: Remove logic for disabling save button
  src/pages/settings/e-invoice/EInvoice.tsx
Labels: QA passed

#2210 [Cleanup] Removing C2C Action For Invoice "Number" Column
  src/pages/invoices/common/hooks/useInvoiceColumns.tsx
Labels: QA passed

#2211 E-invoicing: Gracefully handling 400s
  src/common/helpers/request.ts
Labels: QA passed

#2193 [Feature] Default Gateway Functionality
  src/pages/clients/show/components/Gateways.tsx
Labels: QA passed

#2209 [Cleanup] Adding "Project" Column For Expense Tables
  src/common/interfaces/expense.ts
  src/pages/clients/show/pages/Expenses.tsx
  src/pages/expenses/common/hooks.tsx
  src/pages/expenses/index/Expenses.tsx
  src/pages/vendors/show/pages/Expenses.tsx
Labels: QA passed

#2215 [Cleanup] Select Field Changing | Company Details Page
  src/components/forms/InputCustomField.tsx
  src/pages/settings/company/components/Details.tsx
  src/pages/settings/custom-fields/components/Field.tsx
Labels: QA passed

#2216 [Cleanup] Adjusting Icons For Payment Overview Page
  src/pages/payments/Payment.tsx
  src/pages/payments/edit/PaymentOverviewInvoice.tsx
Labels: QA passed

#2214 E-invoicing: Onboard validation in safer way
  src/pages/settings/e-invoice/peppol/Onboarding.tsx
Labels: QA passed

#2207 E-invoicing: Remove additional identifiers
  src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
Labels: QA passed

#2213 E-invoicing: Add banner for low credits
  src/components/banners/EInvoiceCredits.tsx
Labels: QA passed

#2224 [Bugfix] Fixes For Option Value Types For "Payment Terms" And "Quote Valid Until"
  src/pages/clients/edit/components/AdditionalInfo.tsx
  src/pages/recurring-invoices/common/components/InvoiceDetails.tsx
Labels: QA passed

#2219 [Cleanup] Changed Approach For Triggering "validateEntity" Endpoint
  src/common/hooks/useRefetch.tsx
  src/pages/invoices/Invoice.tsx
  src/pages/invoices/common/hooks/useTabs.tsx
  src/pages/invoices/edit/components/EInvoice.tsx
  src/pages/invoices/edit/components/InvoiceEntityValidationButton.tsx
  src/pages/settings/common/hooks/useHandleCompanySave.tsx
  src/pages/settings/e-invoice/common/hooks/useCheckEInvoiceValidation.ts
Labels: QA passed

#2223 [Cleanup] Changing Selector Fields To New Styling
  src/pages/settings/localization/components/Settings.tsx
  src/pages/settings/user/components/Notifications.tsx
Labels: QA passed

#2204 E-invoicing: Update validator to show custom message
  src/pages/settings/e-invoice/peppol/Preferences.tsx
Labels: QA passed

#2220 Improvements for tax settings
  src/pages/settings/tax-settings/TaxSettings.tsx
Labels: QA passed

#2225 [Cleanup] Adding Missing Templates In Selection Dropdown
  src/components/forms/SelectField.tsx
  src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
Labels: QA passed

#2226 [Cleanup] Adding Icon In Sidebar When Update Is Available
  src/components/AboutModal.tsx
  src/components/HelpSidebarIcons.tsx
  src/components/UpdateAppModal.tsx
Labels: QA passed, pending merge

#2230 [Cleanup] Formatting next_send_datetime Property By Timezone | Recurring Invoices
  src/common/hooks/useCompanyTimeZone.ts
  src/common/hooks/useDateTime.ts
  src/common/hooks/useGetTimezone.ts
  src/pages/dashboard/components/UpcomingRecurringInvoices.tsx
  src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx
  src/pages/recurring-invoices/common/hooks.tsx
Labels: more information requested, QA passed

#2231 [Cleanup] Formatting Date Properties For Invoices With Timezone
  src/pages/invoices/common/components/InvoiceSlider.tsx
  src/pages/invoices/common/hooks/useInvoiceColumns.tsx
Labels: QA passed

#2232 [Cleanup] Formatting Date Properties For Invoices With Timezone
  src/pages/quotes/common/components/QuoteSlider.tsx
Labels: QA passed

#2227 [Cleanup] Select Fields Changing | Payment Settings
  src/components/forms/SelectField.tsx
  src/pages/settings/gateways/create/Create.tsx
  src/pages/settings/gateways/create/components/LimitsAndFees.tsx
  src/pages/settings/gateways/create/components/Settings.tsx
  src/pages/settings/gateways/create/hooks/useResolveInputField.tsx
  src/pages/settings/online-payments/OnlinePayments.tsx
Labels: QA passed

#2229 [Feature] Implementing Backup Section On E-Invoice Tab | Invoice Edit Page
  src/common/interfaces/invoice.ts
  src/pages/invoices/edit/components/EInvoice.tsx
Labels: QA passed

#2233 [Feature] Implementing Common Actions | Quotes
  src/common/hooks/useCommonActions.ts
  src/components/CommonActionsPreferenceModal.tsx
  src/pages/invoices/edit/components/CommonActions.tsx
  src/pages/quotes/Quote.tsx
  src/pages/quotes/common/components/CloneOptionsModal.tsx
  src/pages/quotes/common/components/ConvertToInoviceBulkAction.tsx
  src/pages/quotes/common/components/ConvertToProjectBulkAction.tsx
  src/pages/quotes/common/hooks.tsx
  src/pages/quotes/common/hooks/useCustomBulkActions.tsx
Labels: QA passed

#2239 [Bugfix] Implementing "Eye Icon Functionality" For Unsecure Context
  src/components/CopyToClipboard.tsx
Labels: QA passed

#2237 [Feature] Implementing "Common Actions Section" For Recurring Invoices
  src/common/hooks/useCommonActions.ts
  src/components/CommonActionsPreferenceModal.tsx
  src/pages/invoices/edit/components/CommonActions.tsx
  src/pages/recurring-invoices/RecurringInvoice.tsx
  src/pages/recurring-invoices/common/components/CloneOptionsModal.tsx
  src/pages/recurring-invoices/common/components/IncreasePricesAction.tsx
  src/pages/recurring-invoices/common/components/UpdatePricesAction.tsx
  src/pages/recurring-invoices/common/hooks.tsx
  src/pages/recurring-invoices/common/hooks/useCustomBulkActions.tsx
Labels: QA passed, pending merge
