Repository invoiceninja/ui, pull requests merged in 2024-12, with the labels that each got.

#2241 E-invoice sending settings
  src/pages/invoices/common/hooks/useTabs.tsx
Labels: QA passed

#2242 [Cleanup] Additional Check When Disabling Validation Entity Query
  src/pages/invoices/Invoice.tsx
Labels: QA passed

#2243 [Feature] Implementing "Common Actions Section" | Purchase Orders
  src/common/hooks/useCommonActions.ts
  src/components/CommonActionsPreferenceModal.tsx
  src/pages/invoices/edit/components/CommonActions.tsx
  src/pages/purchase-orders/PurchaseOrder.tsx
  src/pages/purchase-orders/common/components/CloneOptionsModal.tsx
  src/pages/purchase-orders/common/hooks.tsx
Labels: QA passed

#2244 [Cleanup] Updating Payload For Designs Default Endpoint
  src/pages/settings/invoice-design/InvoiceDesign.tsx
Labels: QA passed

#2247 [Bugfix] Missing Mapping Of Custom Fields When Converting Or Adding To Invoice
  src/pages/expenses/common/components/AddToInvoiceAction.tsx
  src/pages/expenses/common/useInvoiceExpense.ts
  src/pages/projects/common/hooks/useInvoiceProject.tsx
Labels: QA passed

#2252 Additional prop for tax model.
  src/common/constants/eu-countries.ts
  src/common/constants/uk-regions.ts
  src/common/hooks/useCalculateTaxesRegion.ts
  src/common/interfaces/company.interface.ts
  src/components/UKRegionSelector.tsx
  src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
  src/pages/settings/tax-settings/components/calculate-taxes/CalculateTaxes.tsx
  src/pages/settings/tax-settings/components/calculate-taxes/components/SellerSubregion.tsx
  src/pages/settings/tax-settings/components/calculate-taxes/components/UKRegions.tsx
Labels: QA passed, pending merge

#2255 Change order of rounding taxes in line items
  src/common/helpers/invoices/invoice-item-sum-inclusive.ts
  src/common/helpers/invoices/invoice-item-sum.ts
  tests/unit/helpers/invoice-sum.test.ts
Labels: QA passed

#2256 Updated translations
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/en_GB/en_GB.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lo_LA/lo_LA.json
  src/resources/lang/lt/lt.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nb_NO/nb_NO.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/ru_RU/ru_RU.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sq/sq.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/th/th.json
  src/resources/lang/tr_TR/tr_TR.json
  src/resources/lang/vi/vi.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#2257 Fixes for peppol calculations
  src/common/helpers/invoices/invoice-sum.ts
Labels: QA passed

#2260 [Bugfix] Fixing Issue For Sorting Number In Reports Preview Table
  src/pages/reports/index/Reports.tsx
Labels: QA passed

#2249 [Bugfix] Security Settings | Web Session Timeout Implementation
  src/App.tsx
  src/common/atoms/password-confirmation.ts
  src/common/helpers/request.ts
  src/common/hooks/useOnWrongPasswordEnter.ts
  src/common/hooks/usePreferences.tsx
  src/common/hooks/useWebSessionTimeout.ts
  src/common/interfaces/company.interface.ts
  src/common/queries/users.ts
  src/components/AboutModal.tsx
  src/components/DocumentsTable.tsx
  src/components/PasswordConfirmation.tsx
  src/components/UpdateAppModal.tsx
  src/pages/clients/common/components/MergeClientModal.tsx
  src/pages/clients/common/components/PurgeClientAction.tsx
  src/pages/clients/common/hooks/usePurgeClient.ts
  src/pages/clients/edit/Edit.tsx
  src/pages/clients/show/components/DeleteDocumentAction.tsx
  src/pages/settings/account-management/component/DangerZone.tsx
  src/pages/settings/account-management/component/SecuritySettings.tsx
  src/pages/settings/company/documents/components/Table.tsx
  src/pages/settings/gateways/edit/components/stripe/ImportCustomers.tsx
  src/pages/settings/integrations/api-tokens/Create.tsx
  src/pages/settings/integrations/api-tokens/Edit.tsx
  src/pages/settings/user/UserDetails.tsx
  src/pages/settings/users/create/Create.tsx
  src/pages/settings/users/edit/Edit.tsx
  src/pages/settings/users/index/Users.tsx
  src/pages/vendors/common/components/MergeVendorsAction.tsx
Labels: QA passed

#2265 Option to use system fonts
  src/App.tsx
  src/common/hooks/useReactSettings.ts
  src/common/hooks/useSystemFonts.ts
  src/pages/settings/user/components/Preferences.tsx
Labels: QA passed

#2258 Notifications: Generic message
  src/App.tsx
  src/common/hooks/useReactSettings.ts
  src/common/hooks/useSockets.ts
  src/common/queries/sockets.ts
  src/components/Notifications.tsx
  src/components/PublicNotificationsModal.tsx
  src/components/layouts/Default.tsx
  src/pages/settings/user/components/Preferences.tsx
Labels: QA passed, waiting for @beganovich

#2267 [Bugfix] Incorrect Formatting Of Hours In Description When Invoicing Task
  src/pages/tasks/common/hooks/useInvoiceTask.ts
Labels: QA passed

#2269 [Bugfix] Table Horizontal Scroll
  src/components/tables/Table.tsx
Labels: QA passed

#2270 [Cleanup] Changing Translation Keyword For Counting Tasks
  src/pages/projects/show/Show.tsx
Labels: QA passed

#2271 [Cleanup] Removing Toaster For /quota Endpoint Errors
  src/common/helpers/request.ts
Labels: QA passed

#2273 [Cleanup] Reordering Cards On Gateway Creation Page
  src/pages/settings/gateways/create/Create.tsx
Labels: QA passed

#2274 [Feature] Implementing "Activity" Tab For Vendor Show Page
  src/common/hooks/useRefetch.tsx
  src/pages/vendors/Vendor.tsx
  src/pages/vendors/routes.tsx
  src/pages/vendors/show/hooks/useTabs.tsx
  src/pages/vendors/show/pages/Activities.tsx
Labels: QA passed

#2268 Toggle inclusive taxes off when calculate is enabled
  src/pages/settings/tax-settings/TaxSettings.tsx
Labels: QA passed

#2275 Fixes for socket preferences
  src/App.tsx
  src/components/layouts/Default.tsx
Labels: QA passed

#2250 [Cleanup] Implementing Modal For Search Field In The Top Navbar
  src/components/Modal.tsx
  src/components/forms/InputField.tsx
  src/pages/dashboard/components/Search.tsx
Labels: QA passed

#2278 Fixes for einvoice errors handling
  src/pages/settings/e-invoice/peppol/Onboarding.tsx
Labels: QA passed

#2264 [Feature] Implementing Delete Functionality For Gateway Tokens
  src/components/dropdown/Dropdown.tsx
  src/pages/clients/show/components/ClientPrivateNotes.tsx
  src/pages/clients/show/components/ClientPublicNotes.tsx
  src/pages/clients/show/components/EmailHistory.tsx
  src/pages/clients/show/components/Gateways.tsx
  src/pages/recurring-invoices/common/components/ConfirmActionModal.tsx
Labels: QA passed

#2280 Fixes for mobile navigation
  src/components/Tabs.tsx
  src/pages/settings/company/CompanyDetails.tsx
Labels: QA passed

#2282 [Bugfix] Creating/Remvoing KeyDown Events For Search Modal
  src/pages/dashboard/components/Search.tsx
Labels: QA passed
