Repository invoiceninja/ui, pull requests merged in 2024-08, with the labels that each got.

#1917 [Cleanup] Making Currency Selector Dismissable && Fixing Recurring Expense Currency Converter
  src/pages/expenses/create/components/AdditionalInfo.tsx
  src/pages/expenses/create/components/Details.tsx
  src/pages/recurring-expenses/components/AdditionalInfo.tsx
  src/pages/recurring-expenses/components/Details.tsx
Labels: QA passed

#1922 [Cleanup] Adjusting "prose" Class For Dark Mode | Markdowns
  src/pages/clients/common/hooks/useClientColumns.tsx
  src/pages/clients/show/components/ClientPrivateNotes.tsx
  src/pages/clients/show/components/ClientPublicNotes.tsx
  src/pages/credits/common/hooks.tsx
  src/pages/expenses/common/hooks.tsx
  src/pages/invoices/common/components/InvoiceSlider.tsx
  src/pages/invoices/common/hooks/useInvoiceColumns.tsx
  src/pages/payments/common/hooks/usePaymentColumns.tsx
  src/pages/products/common/hooks.tsx
  src/pages/projects/common/hooks.tsx
  src/pages/projects/show/components/ProjectPrivateNotes.tsx
  src/pages/projects/show/components/ProjectPublicNotes.tsx
  src/pages/quotes/common/components/QuoteSlider.tsx
  src/pages/quotes/common/hooks.tsx
  src/pages/recurring-expenses/common/hooks.tsx
  src/pages/recurring-invoices/common/hooks.tsx
  src/pages/tasks/common/hooks.tsx
  src/pages/transactions/common/hooks/useTransactionColumns.tsx
  src/pages/vendors/common/hooks.tsx
Labels: QA passed

#1921 [Cleanup] Replacing "filter_deleted_clients" Query Param With "without_deleted_clients"
  src/common/hooks/useRefetch.tsx
  src/pages/credits/index/Credits.tsx
  src/pages/dashboard/components/ExpiredQuotes.tsx
  src/pages/dashboard/components/PastDueInvoices.tsx
  src/pages/dashboard/components/RecentPayments.tsx
  src/pages/dashboard/components/UpcomingInvoices.tsx
  src/pages/dashboard/components/UpcomingQuotes.tsx
  src/pages/dashboard/components/UpcomingRecurringInvoices.tsx
  src/pages/invoices/index/Invoices.tsx
  src/pages/payments/index/Payments.tsx
  src/pages/projects/index/Projects.tsx
  src/pages/quotes/index/Quotes.tsx
  src/pages/recurring-invoices/index/RecurringInvoices.tsx
Labels: QA passed

#1924 [Bugfix] Label When Self-hosted Plan Is Paid
  src/pages/settings/account-management/component/Plan.tsx
Labels: QA passed

#1928 [Bugfix] Removing "New User" Option From Email Settings Selector
  src/components/users/UserSelector.tsx
  src/pages/settings/email-settings/EmailSettings.tsx
Labels: QA passed

#1926 [Bugfix] Displaying Client Custom Fields
  src/components/CustomField.tsx
  src/pages/clients/show/components/Details.tsx
Labels: QA passed

#1936 Additional export props
  src/common/constants/exports/task-map.ts
Labels: QA passed

#1942 [Bugfix] Displaying Hidden Save Button On Smaller Screens
  src/components/layouts/Default.tsx
Labels: QA passed

#1943 [Bugfix] Changing "product_key" After Entering Text In Product Selector
  src/components/forms/Combobox.tsx
  src/components/products/ProductSelector.tsx
  src/pages/invoices/common/hooks/useResolveInputField.tsx
Labels: QA passed

#1939 [Feature] Default Quantity While Creating Line Items
  src/pages/credits/common/hooks.tsx
  src/pages/invoices/common/hooks/useHandleProductChange.ts
  src/pages/invoices/common/hooks/useProductColumns.ts
  src/pages/invoices/create/hooks/useInvoiceUtilities.ts
  src/pages/purchase-orders/edit/hooks/useHandleCreateLineItem.ts
  src/pages/quotes/common/hooks.tsx
  src/pages/recurring-invoices/common/hooks.tsx
Labels: QA passed

#1944 [Bugfix] Replaced Wrong Translation Function
  src/pages/dashboard/components/PastDueInvoices.tsx
  src/pages/dashboard/components/RecentPayments.tsx
  src/pages/dashboard/components/UpcomingInvoices.tsx
  src/pages/dashboard/components/UpcomingRecurringInvoices.tsx
  src/pages/dashboard/hooks/useGenerateActivityElement.tsx
  src/pages/projects/common/hooks/useInvoiceProject.tsx
  src/pages/reports/common/components/SortableColumns.tsx
  src/pages/tasks/common/hooks/useAddTasksOnInvoice.ts
Labels: QA passed

#1872 [Cleanup] Prevent Page Leaving Reimplementation
  .env.example
  src/common/hooks/useAtomWithPrevent.ts
  src/common/hooks/usePreventNavigation.ts
  src/components/EntityActionElement.tsx
  src/components/PreventNavigationModal.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/invoices/edit/components/Actions.tsx
Labels: QA passed

#1933 Fixes for client number label
  src/pages/clients/common/hooks/useClientColumns.tsx
Labels: QA passed

#1945 [Bugfix] Hiding Permissions Section | Health Check
  src/components/AboutModal.tsx
Labels: QA passed

#1923 [Feature] Implementing Links For Expenses And Tasks | Invoices
  src/pages/invoices/common/components/InvoiceSlider.tsx
  src/pages/invoices/common/components/ViewLineItemExpense.tsx
  src/pages/invoices/common/components/ViewLineItemTask.tsx
Labels: QA passed

#1948 Change transactions bitmask
  src/pages/settings/account-management/component/EnabledModules.tsx
Labels: QA passed

#1951 Improve URLs for client portal
  src/pages/settings/client-portal/components/Registration.tsx
  src/pages/settings/client-portal/components/Settings.tsx
  src/pages/settings/invoice-design/pages/general-settings/components/TotalFields.tsx
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lo_LA/lo_LA.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/tr_TR/tr_TR.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#1953 [Bugfix] Setting "product_key" Through Combo Input Value && Test Implementation
  src/components/forms/Combobox.tsx
  src/components/products/ProductSelector.tsx
  src/pages/invoices/common/hooks/useResolveInputField.tsx
  tests/e2e/invoices.spec.ts
Labels: QA passed

#1952 [Bugfix] White Screen When Restoring Payment
  src/pages/settings/gateways/create/components/LimitsAndFees.tsx
Labels: QA passed

#1956 [Bugfix] Breadcrumbs Issue On Tax Rates and Task Statuses Pages | Production Issue
  src/pages/settings/task-statuses/Create.tsx
  src/pages/settings/task-statuses/Edit.tsx
  src/pages/settings/tax-rates/Create.tsx
  src/pages/settings/tax-rates/Edit.tsx
Labels: QA passed

#1958 [Bugfix] Creating Invoices and Purchase Orders From Products
  src/pages/products/common/hooks/useInvoiceProducts.ts
  src/pages/products/common/hooks/usePurchaseOrderProducts.ts
Labels: QA passed

#1961 [Bugfix] Displaying Activities On Invoice Edit Page
  src/common/interfaces/invoice-activity.ts
  src/pages/invoices/common/components/InvoiceSlider.tsx
  src/pages/invoices/edit/components/Activities.tsx
Labels: QA passed

#1733 [Feature] E-Invoice Scaffold
  .env.example
  package-lock.json
  package.json
  src/common/interfaces/company.interface.ts
  src/common/interfaces/credit.ts
  src/common/interfaces/expense.ts
  src/common/interfaces/invoice.ts
  src/common/interfaces/purchase-order.ts
  src/common/interfaces/quote.ts
  src/components/SettingsLabel.tsx
  src/components/e-invoice/EInvoiceBreadcrumbs.tsx
  src/components/e-invoice/EInvoiceFieldCheckbox.tsx
  src/components/e-invoice/EInvoiceGenerator.tsx
  src/components/e-invoice/EInvoiceValidationAlert.tsx
  src/components/layouts/common/hooks.ts
  src/pages/invoices/edit/components/EInvoice.tsx
  src/pages/settings/e-invoice/EInvoice.tsx
  src/pages/settings/email-settings/EmailSettings.tsx
  src/pages/settings/index.ts
  src/pages/settings/routes.tsx
  src/resources/e-invoice/peppol/peppol.json
Labels: QA passed

#1957 [Bugfix] More Descriptive Message On Modal | Health Check | Gateways
  src/pages/settings/gateways/create/components/Credentials.tsx
  src/pages/settings/gateways/edit/Edit.tsx
Labels: QA passed

#1978 Additional Translations
  src/resources/lang/ar/ar.json
  src/resources/lang/bg/bg.json
  src/resources/lang/ca/ca.json
  src/resources/lang/cs/cs.json
  src/resources/lang/da/da.json
  src/resources/lang/de/de.json
  src/resources/lang/el/el.json
  src/resources/lang/en/en.json
  src/resources/lang/en_GB/en_GB.json
  src/resources/lang/es/es.json
  src/resources/lang/es_ES/es_ES.json
  src/resources/lang/et/et.json
  src/resources/lang/fa/fa.json
  src/resources/lang/fi/fi.json
  src/resources/lang/fr/fr.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/fr_CH/fr_CH.json
  src/resources/lang/he/he.json
  src/resources/lang/hr/hr.json
  src/resources/lang/hu/hu.json
  src/resources/lang/it/it.json
  src/resources/lang/ja/ja.json
  src/resources/lang/km_KH/km_KH.json
  src/resources/lang/lo_LA/lo_LA.json
  src/resources/lang/lt/lt.json
  src/resources/lang/lv_LV/lv_LV.json
  src/resources/lang/mk_MK/mk_MK.json
  src/resources/lang/nb_NO/nb_NO.json
  src/resources/lang/nl/nl.json
  src/resources/lang/pl/pl.json
  src/resources/lang/pt_BR/pt_BR.json
  src/resources/lang/pt_PT/pt_PT.json
  src/resources/lang/ro/ro.json
  src/resources/lang/ru_RU/ru_RU.json
  src/resources/lang/sk/sk.json
  src/resources/lang/sl/sl.json
  src/resources/lang/sq/sq.json
  src/resources/lang/sr/sr.json
  src/resources/lang/sv/sv.json
  src/resources/lang/th/th.json
  src/resources/lang/tr_TR/tr_TR.json
  src/resources/lang/zh_TW/zh_TW.json
Labels: QA passed

#1979 [Bugfix] Documents Permissions
  src/pages/clients/edit/components/AdditionalInfo.tsx
  src/pages/credits/edit/components/Documents.tsx
  src/pages/expenses/documents/Documents.tsx
  src/pages/invoices/edit/components/Documents.tsx
  src/pages/payments/documents/Documents.tsx
  src/pages/products/documents/Documents.tsx
  src/pages/projects/documents/Documents.tsx
  src/pages/purchase-orders/edit/components/Footer.tsx
  src/pages/quotes/edit/components/Documents.tsx
  src/pages/recurring-expenses/documents/Documents.tsx
  src/pages/recurring-invoices/edit/components/Documents.tsx
  src/pages/tasks/documents/Documents.tsx
  src/pages/tasks/kanban/components/ViewSlider.tsx
  src/pages/vendors/show/pages/Documents.tsx
Labels: QA passed

#1981 [Bugfix] Company Index Issue
  src/common/guards/guards/enabled.ts
Labels: QA passed

#1987 [Bugfix] Adjusting Documents Table Permissions
  src/pages/clients/edit/components/AdditionalInfo.tsx
  src/pages/credits/common/components/CreditFooter.tsx
  src/pages/expenses/documents/Documents.tsx
  src/pages/invoices/edit/components/Documents.tsx
  src/pages/payments/documents/Documents.tsx
  src/pages/products/documents/Documents.tsx
  src/pages/projects/documents/Documents.tsx
  src/pages/purchase-orders/edit/components/Footer.tsx
  src/pages/quotes/common/components/QuoteFooter.tsx
  src/pages/recurring-expenses/documents/Documents.tsx
  src/pages/recurring-invoices/common/components/InvoiceFooter.tsx
  src/pages/tasks/documents/Documents.tsx
  src/pages/tasks/kanban/components/ViewSlider.tsx
  src/pages/vendors/show/pages/Documents.tsx
Labels: QA passed

#1975 Indicator that task is running in tasks table
  src/pages/tasks/common/components/DurationClock.tsx
  src/pages/tasks/common/components/TaskTable.tsx
Labels: QA passed

#1989 Fixes for empty client on invoicing the project
  src/pages/projects/common/hooks.tsx
  src/pages/projects/common/hooks/useInvoiceProject.tsx
Labels: QA passed, hot patch

#1982 Implemented uploading xml files on expense import page
  src/components/import/XMLImport.tsx
  src/pages/expenses/import/Import.tsx
Labels: QA passed

#1996 [Bugfix] Matching Currency Format Symbol With Selected Currency
  src/common/hooks/money/useFormatMoney.ts
  src/pages/settings/localization/components/Settings.tsx
Labels: QA passed

#1995 Fixes for creating new tasks
  src/pages/tasks/common/components/TaskTable.tsx
Labels: QA passed

#1999 [Feature] New Purchase Order Event
  src/pages/settings/integrations/api-webhooks/common/hooks/useEvents.ts
Labels: QA passed

#1991 [Bugfix] Invalid Task Time Log Values Handling
  src/pages/tasks/common/components/TaskTable.tsx
Labels: QA passed

#1997 [Bugfix] Recalculating Task Timer On Saving
  src/pages/tasks/kanban/components/TaskClock.tsx
Labels: QA passed

#1992 [Bugfix] Covering Edge Case For "Custom" Date Range | Dashboard Chart
  src/pages/dashboard/components/Chart.tsx
  src/pages/dashboard/components/Totals.tsx
  src/pages/dashboard/helpers/helpers.ts
Labels: QA passed

#2003 Refactor formatting numbers
  src/common/helpers/number-format.ts
  tests/unit/helpers/invoice-number.test.ts
Labels: QA passed

#2001 [Cleanup] Implementing Searchable Select Field | Webhooks
  src/pages/settings/integrations/api-webhooks/Create.tsx
  src/pages/settings/integrations/api-webhooks/Edit.tsx
Labels: QA passed

#2007 [Cleanup] Adjusting The "per_page" Query Parameter On Expense Category Selector
  src/components/expense-categories/ExpenseCategorySelector.tsx
Labels: QA passed

#2002 [Bugfix] Handling 422 On Reports Page
  src/pages/reports/index/Reports.tsx
Labels: QA passed

#2009 [Bugfix] Nested Modals Focusing Field Issue
  package-lock.json
  package.json
  src/components/Modal.tsx
  src/components/PasswordConfirmation.tsx
Labels: QA passed

#2012 [Bugfix] Invoicing Expense | Query Invalidation
  src/pages/invoices/create/hooks/useHandleCreate.ts
Labels: QA passed

#2010 [Feature] Implementing "Add Item" Button | Invoices
  src/components/expenses/ExpenseSelector.tsx
  src/components/products/ProductSelector.tsx
  src/components/tasks/TaskSelector.tsx
  src/pages/expenses/common/hooks.tsx
  src/pages/expenses/common/useInvoiceExpense.ts
  src/pages/invoices/Invoice.tsx
  src/pages/invoices/common/components/AddUninvoicedItemsButton.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/products/common/hooks/useInvoiceProducts.ts
  src/pages/tasks/common/hooks/useInvoiceTask.ts
Labels: QA passed

#2014 [Feature] Implementing Additional Expense Filter Selector
  src/pages/expenses/common/hooks.tsx
Labels: QA passed

#2015 [Feature] Signature Field | User Details
  src/pages/settings/user/components/Details.tsx
Labels: QA passed

#2016 [Bugfix] Returning Headless Package To Old Version
  package-lock.json
  package.json
  src/components/AboutModal.tsx
  src/components/forms/Combobox.tsx
Labels: QA pending
