Repository invoiceninja/ui, pull requests merged in 2025-01, with the labels that each got.

#2283 Remove public notifications modal
  src/components/PublicNotificationsModal.tsx
  src/components/layouts/Default.tsx
  src/pages/settings/user/components/Preferences.tsx
Labels: QA passed

#2288 [Cleanup] Adding Missing Payment Type Translations
  src/common/constants/payment-type.ts
  src/common/enums/payment-type.ts
Labels: QA passed

#2290 [Feature] Implementing Checkbox For Selecting All Expenses | Transaction Slider
  src/pages/transactions/components/ListBox.tsx
  src/pages/transactions/components/TransactionMatchDetails.tsx
Labels: QA passed

#2289 [Cleanup] Implementing "Plan" Banner For E-Invoice Page
  src/components/AdvancedSettingsPlanAlert.tsx
  src/pages/settings/e-invoice/EInvoice.tsx
  src/pages/settings/e-invoice/common/components/PEPPOLPlanBanner.tsx
Labels: QA passed

#2292 [Bugfix] Making "Connect/Disconnect Gmail/Microsoft" Options Only For Paid Plans
  src/pages/settings/user/common/hooks/useUserDetailsTabs.tsx
  src/pages/settings/user/components/Connect.tsx
Labels: QA passed

#2285 [Cleanup] Refactoring Of Invoice Project Functionality
  src/pages/projects/common/hooks.tsx
  src/pages/projects/common/hooks/useBulkAction.ts
  src/pages/projects/common/hooks/useCombineProjectsTasks.ts
  src/pages/projects/common/hooks/useInvoiceProject.tsx
Labels: QA passed

#2291 [Feature] Implementing "Previous/Next" Icons | Recurring Invoices
  src/components/PreviousNextNavigation.tsx
  src/components/layouts/Default.tsx
  src/pages/clients/edit/Edit.tsx
  src/pages/clients/show/Client.tsx
  src/pages/credits/Credit.tsx
  src/pages/expenses/Expense.tsx
  src/pages/invoices/Invoice.tsx
  src/pages/payments/Payment.tsx
  src/pages/products/Product.tsx
  src/pages/products/index/Products.tsx
  src/pages/projects/Project.tsx
  src/pages/projects/show/Show.tsx
  src/pages/purchase-orders/PurchaseOrder.tsx
  src/pages/quotes/Quote.tsx
  src/pages/recurring-expenses/RecurringExpense.tsx
  src/pages/recurring-invoices/RecurringInvoice.tsx
  src/pages/tasks/Task.tsx
  src/pages/transactions/edit/Edit.tsx
  src/pages/vendors/Vendor.tsx
  src/pages/vendors/edit/Edit.tsx
Labels: QA passed

#2294 [Feature] Implementing "Calculate Taxes" Modal As Confirmation
  src/pages/settings/tax-settings/TaxSettings.tsx
  src/pages/settings/tax-settings/components/calculate-taxes/components/CalculateTaxesNotificationModal.tsx
Labels: QA passed

#2295 [Bugfix] Input Value Changes On Product Selector
  src/components/forms/Combobox.tsx
Labels: more information requested, QA passed

#2300 [Cleanup] Implementing New Approach For Saving Table Filters
  src/common/hooks/useDataTablePreference.ts
  src/common/hooks/useDataTablePreferences.ts
  src/common/hooks/useDataTableUtilities.ts
  src/common/hooks/useStoreSessionTableFilters.ts
  src/components/DataTable.tsx
  src/pages/clients/index/Clients.tsx
  src/pages/credits/index/Credits.tsx
  src/pages/expenses/index/Expenses.tsx
  src/pages/invoices/index/Invoices.tsx
  src/pages/payments/index/Payments.tsx
  src/pages/products/index/Products.tsx
  src/pages/projects/index/Projects.tsx
  src/pages/purchase-orders/index/PurchaseOrders.tsx
  src/pages/quotes/index/Quotes.tsx
  src/pages/recurring-expenses/index/RecurringExpenses.tsx
  src/pages/recurring-invoices/index/RecurringInvoices.tsx
  src/pages/settings/bank-accounts/components/transaction-rules/TransactionRules.tsx
  src/pages/settings/bank-accounts/index/BankAccounts.tsx
  src/pages/settings/expense-categories/ExpenseCategories.tsx
  src/pages/settings/group-settings/index/GroupSettings.tsx
  src/pages/settings/integrations/api-tokens/ApiTokens.tsx
  src/pages/settings/integrations/api-webhooks/ApiWebhooks.tsx
  src/pages/settings/invoice-design/pages/custom-designs/index/CustomDesigns.tsx
  src/pages/settings/payment-terms/PaymentTerms.tsx
  src/pages/settings/schedules/index/Schedules.tsx
  src/pages/settings/subscriptions/index/Subscriptions.tsx
  src/pages/settings/task-statuses/TaskStatuses.tsx
  src/pages/settings/tax-rates/TaxRates.tsx
  src/pages/settings/users/index/Users.tsx
  src/pages/tasks/index/Tasks.tsx
  src/pages/transactions/index/Transactions.tsx
  src/pages/vendors/index/Vendors.tsx
Labels: QA passed

#2299 Slider fixes & improvements
  src/components/TabGroup.tsx
  src/components/cards/Slider.tsx
  src/pages/invoices/common/components/InvoiceSlider.tsx
  src/pages/payments/common/components/PaymentSlider.tsx
  src/pages/quotes/common/components/QuoteSlider.tsx
  src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx
  src/pages/tasks/common/components/TaskSlider.tsx
  src/pages/tasks/kanban/components/ViewSlider.tsx
Labels: QA passed

#2259 Resizable tables
  src/common/hooks/useResizeColumn.ts
  src/components/DataTable.tsx
  src/components/tables/Table.tsx
  src/components/tables/Td.tsx
  src/components/tables/Th.tsx
Labels: QA passed, waiting for @beganovich

#2302 E-invoicing: Fixes for GB identifiers
  src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
Labels: QA passed

#2306 Updated translations
  src/resources/lang/de/de.json
  src/resources/lang/en/en.json
  src/resources/lang/en_GB/en_GB.json
  src/resources/lang/fr_CA/fr_CA.json
  src/resources/lang/vi/vi.json
Labels: QA passed

#2262 [Bugfix] Removing Default Quick Actions
  src/common/hooks/useCommonActions.ts
  src/common/hooks/useShowActionByPreferences.ts
  src/pages/invoices/edit/components/CommonActions.tsx
Labels: QA passed

#2311 [Bugfix] Invalidating Cache When Updating All Records [Designs]
  src/common/hooks/useRefetch.tsx
  src/common/queries/designs.ts
  src/pages/settings/invoice-design/InvoiceDesign.tsx
Labels: QA passed

#2309 [Bugfix] Email Preview Page Template Issue
  src/common/hooks/emails/useResolveTemplate.ts
  src/components/forms/MarkdownEditor.tsx
  src/pages/invoices/email/components/Mailer.tsx
  src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
Labels: QA passed

#2308 [Bugfix] Selector Menu Not Visibile On Line Items Table
  src/components/CustomField.tsx
  src/components/forms/InputCustomField.tsx
  src/components/forms/SelectField.tsx
  src/pages/invoices/common/hooks/useResolveInputField.tsx
Labels: question, QA passed

#2313 [Bugfix] Hiding "Disable 2FA" Functionality For Self-Hosted Users
  src/pages/authentication/Login.tsx
Labels: QA passed

#2315 [Bugfix] "Line Total" Column On Line Items Table
  src/pages/invoices/common/hooks/useProductColumns.ts
  src/pages/invoices/common/hooks/useTaskColumns.ts
  src/pages/settings/invoice-design/pages/general-settings/components/ProductColumns.tsx
  src/pages/settings/invoice-design/pages/general-settings/components/TaskColumns.tsx
Labels: QA passed

#2314 [Cleanup] Invoice Shortcut Option Reversal on Edit Page
  src/common/constants/invoice-status.ts
  src/common/queries/invoices.ts
  src/pages/invoices/common/hooks/useTabs.tsx
  src/pages/invoices/edit/Edit.tsx
  src/pages/invoices/edit/components/Payments.tsx
  src/pages/invoices/routes.tsx
Labels: QA passed

#2319 [Bugfix] Debounce Subject And Body Changing Value Instead of onBlur
  src/components/forms/InputField.tsx
  src/components/forms/MarkdownEditor.tsx
  src/pages/invoices/email/components/Mailer.tsx
Labels: QA passed

#2320 [Cleanup] Duplicating Gateways Notification Modal
  src/common/queries/company-gateways.ts
  src/pages/settings/gateways/create/Create.tsx
  src/pages/settings/gateways/create/components/DuplicatingGatewayModal.tsx
Labels: QA passed

#2321 [Bugfix] Adding Maximum Clients Validation Message On Client Create Modal
  src/pages/invoices/common/components/ClientCreate.tsx
Labels: QA passed

#2327 [Bugfix] Bell Icon Dark Mode Color Issue
  src/components/Notifications.tsx
Labels: QA passed

#2328 [Bugfix] Number Rounding Issue | Footer Columns
  src/common/hooks/useSumTableColumn.ts
Labels: QA passed

#2326 Fixes for date range column handling
  src/components/DataTable.tsx
  src/components/datatables/DateRangePicker.tsx
Labels: QA passed

#2317 [Feature] Adding "Leave Page" Functionality To Invoices, Credits and Purchase Orders
  src/common/hooks/useAtomWithPrevent.ts
  src/components/PreviousNextNavigation.tsx
  src/pages/credits/Credit.tsx
  src/pages/credits/common/hooks.tsx
  src/pages/credits/create/Create.tsx
  src/pages/invoices/Invoice.tsx
  src/pages/invoices/create/Create.tsx
  src/pages/invoices/edit/components/Actions.tsx
  src/pages/purchase-orders/PurchaseOrder.tsx
  src/pages/purchase-orders/common/hooks.tsx
  src/pages/purchase-orders/create/Create.tsx
  src/pages/quotes/common/hooks.tsx
Labels: QA passed

#2329 [Cleanup] Purge Client Warning/Confirmation Modal
  src/pages/clients/common/components/PurgeClientAction.tsx
Labels: QA passed

#2331 Update translation for default payment method
  src/pages/clients/show/components/Gateways.tsx
Labels: QA passed

#2332 Coalesce recurring invoice Save / More Actions buttons
  src/pages/recurring-invoices/RecurringInvoice.tsx
  src/pages/recurring-invoices/common/hooks.tsx
Labels: QA passed

#2333 [Bugfix] Display Value Formatting Issue | Reports
  src/pages/reports/common/constants/columns.ts
  src/pages/reports/index/Reports.tsx
Labels: QA passed

#2334 [Bugfix] Non-Persisting Payment Means Setting | E-Invoice
  src/components/e-invoice/PaymentMeans.tsx
Labels: QA passed

#2336 [Bugfix] Disabling Prevent Leaving Page Functionality When Invoice Is Locked
  src/common/hooks/useAtomWithPrevent.ts
  src/pages/invoices/Invoice.tsx
Labels: QA passed
